package com.hogaria.service;
import com.hogaria.dto.MonthlyPlanDtos.*;import com.hogaria.entity.*;import com.hogaria.exception.BadRequestException;import com.hogaria.repository.*;import org.junit.jupiter.api.Test;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.*;import org.mockito.junit.jupiter.MockitoExtension;import java.math.*;import java.time.LocalDate;import java.util.*;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class)
@org.mockito.junit.jupiter.MockitoSettings(strictness = org.mockito.quality.Strictness.LENIENT)
class MonthlyPlanServiceTest {
 @Mock MonthlyPlanItemRepository repo; @Mock FinancialProfileRepository profiles; @Mock CategoryRepository categories; @Mock AccountRepository accounts; @Mock MoneyTransactionRepository txRepo; @InjectMocks MonthlyPlanService s;
 UUID u=UUID.randomUUID(), p=UUID.randomUUID(), c=UUID.randomUUID(), a=UUID.randomUUID();
 void ok(){ when(profiles.findByIdAndUserId(p,u)).thenReturn(Optional.of(new FinancialProfile())); when(accounts.existsByIdAndProfileId(a,p)).thenReturn(true); var cat=new Category(); cat.setProfileId(p); when(categories.findById(c)).thenReturn(Optional.of(cat)); }
 @Test void creaItemExacto(){ ok(); var req=new MonthlyPlanItemCreateRequest(MonthlyPlanItem.Type.EXPENSE,"Colegio",null,LocalDate.now(),2026,5,new BigDecimal("10"),null,null,"ARS",null,null,null,null,null,null,null,null,c,a); when(repo.save(any())).thenAnswer(i->i.getArgument(0)); assertEquals(new BigDecimal("10"), s.create(u,p,req).amount()); }
 @Test void creaItemConRango(){ ok(); var req=new MonthlyPlanItemCreateRequest(MonthlyPlanItem.Type.EXPENSE,"x",null,null,2026,5,null,new BigDecimal("10"),new BigDecimal("20"),"ARS",null,null,null,null,null,null,null,null,c,a); when(repo.save(any())).thenAnswer(i->i.getArgument(0)); assertEquals(new BigDecimal("20"), s.create(u,p,req).maxAmount()); }
 @Test void netoConRecuperoPorcentual(){ ok(); var i=MonthlyPlanItem.builder().profileId(p).type(MonthlyPlanItem.Type.EXPENSE).title("x").periodYear(2026).periodMonth(5).amount(new BigDecimal("100")).expectedRecoveryPercent(new BigDecimal("50")).build(); when(repo.findByProfileIdAndPeriodYearAndPeriodMonth(p,2026,5)).thenReturn(List.of(i)); assertEquals(new BigDecimal("-50.000000"), s.summary(u,p,2026,5).netMin()); }
 @Test void netoConRecuperoFijo(){ ok(); var i=MonthlyPlanItem.builder().profileId(p).type(MonthlyPlanItem.Type.EXPENSE).title("x").periodYear(2026).periodMonth(5).amount(new BigDecimal("100")).expectedRecoveryAmount(new BigDecimal("20")).build(); when(repo.findByProfileIdAndPeriodYearAndPeriodMonth(p,2026,5)).thenReturn(List.of(i)); assertEquals(new BigDecimal("-80"), s.summary(u,p,2026,5).netMin()); }
 @Test void cuentaSinCotizar(){ ok(); var i=MonthlyPlanItem.builder().profileId(p).type(MonthlyPlanItem.Type.TODO).title("x").periodYear(2026).periodMonth(5).build(); when(repo.findByProfileIdAndPeriodYearAndPeriodMonth(p,2026,5)).thenReturn(List.of(i)); assertEquals(1, s.summary(u,p,2026,5).unpricedCount()); }
 @Test void noConvierteSinDatos(){ ok(); var i=MonthlyPlanItem.builder().id(UUID.randomUUID()).profileId(p).type(MonthlyPlanItem.Type.EXPENSE).title("x").periodYear(2026).periodMonth(5).build(); when(repo.findByIdAndProfileId(i.getId(),p)).thenReturn(Optional.of(i)); assertThrows(BadRequestException.class,()->s.convert(u,p,i.getId())); }
 @Test void convierteIncome(){ ok(); var i=MonthlyPlanItem.builder().id(UUID.randomUUID()).profileId(p).type(MonthlyPlanItem.Type.INCOME).title("x").periodYear(2026).periodMonth(5).amount(new BigDecimal("10")).accountId(a).categoryId(c).build(); when(repo.findByIdAndProfileId(i.getId(),p)).thenReturn(Optional.of(i)); when(txRepo.save(any())).thenAnswer(x->{var t=x.getArgument(0, MoneyTransaction.class); t.setId(UUID.randomUUID()); return t;}); when(repo.save(any())).thenAnswer(x->x.getArgument(0)); assertEquals(MonthlyPlanItem.Status.COLLECTED,s.convert(u,p,i.getId()).status()); }
 @Test void convierteExpense(){ ok(); var i=MonthlyPlanItem.builder().id(UUID.randomUUID()).profileId(p).type(MonthlyPlanItem.Type.EXPENSE).title("x").periodYear(2026).periodMonth(5).amount(new BigDecimal("10")).accountId(a).categoryId(c).build(); when(repo.findByIdAndProfileId(i.getId(),p)).thenReturn(Optional.of(i)); when(txRepo.save(any())).thenAnswer(x->{var t=x.getArgument(0, MoneyTransaction.class); t.setId(UUID.randomUUID()); return t;}); when(repo.save(any())).thenAnswer(x->x.getArgument(0)); assertEquals(MonthlyPlanItem.Status.PAID,s.convert(u,p,i.getId()).status()); }
}
