package com.hogaria.service;
import com.hogaria.dto.MonthlyPlanDtos.*;import com.hogaria.entity.*;import com.hogaria.exception.BadRequestException;import com.hogaria.repository.*;import org.junit.jupiter.api.Test;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.*;import org.mockito.junit.jupiter.MockitoExtension;import java.math.*;import java.time.LocalDate;import java.util.*;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class)
@org.mockito.junit.jupiter.MockitoSettings(strictness = org.mockito.quality.Strictness.LENIENT)
class MonthlyPlanServiceTest {
 @Mock MonthlyPlanItemRepository repo; @Mock FinancialProfileRepository profiles; @Mock CategoryRepository categories; @Mock AccountRepository accounts; @Mock MoneyTransactionRepository txRepo; @Mock MonthlyPlanTransactionMatchRepository matchRepo; @InjectMocks MonthlyPlanService s;
 UUID u=UUID.randomUUID(), p=UUID.randomUUID(), c=UUID.randomUUID(), a=UUID.randomUUID();
 void ok(){ when(profiles.findByIdAndUserId(p,u)).thenReturn(Optional.of(new FinancialProfile())); when(accounts.existsByIdAndProfileId(a,p)).thenReturn(true); var cat=new Category(); cat.setProfileId(p); when(categories.findById(c)).thenReturn(Optional.of(cat)); }
 MonthlyPlanItemUpdateRequest updateReq(LocalDate expectedDate,Integer periodYear,Integer periodMonth){ return new MonthlyPlanItemUpdateRequest(null,null,null,expectedDate,periodYear,periodMonth,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null); }
 @Test void creaItemExacto(){ ok(); var req=new MonthlyPlanItemCreateRequest(MonthlyPlanItem.Type.EXPENSE,"Colegio",null,LocalDate.of(2026,5,10),2026,5,new BigDecimal("10"),null,null,"ARS",null,null,null,null,null,null,null,null,c,a); when(repo.save(any())).thenAnswer(i->i.getArgument(0)); assertEquals(new BigDecimal("10"), s.create(u,p,req).amount()); }
 @Test void creaItemConRango(){ ok(); var req=new MonthlyPlanItemCreateRequest(MonthlyPlanItem.Type.EXPENSE,"x",null,null,2026,5,null,new BigDecimal("10"),new BigDecimal("20"),"ARS",null,null,null,null,null,null,null,null,c,a); when(repo.save(any())).thenAnswer(i->i.getArgument(0)); assertEquals(new BigDecimal("20"), s.create(u,p,req).maxAmount()); }
 @Test void netoConRecuperoPorcentual(){ ok(); var i=MonthlyPlanItem.builder().profileId(p).type(MonthlyPlanItem.Type.EXPENSE).title("x").periodYear(2026).periodMonth(5).amount(new BigDecimal("100")).expectedRecoveryPercent(new BigDecimal("50")).build(); when(repo.findByProfileIdAndPeriodYearAndPeriodMonth(p,2026,5)).thenReturn(List.of(i)); assertEquals(new BigDecimal("-50.000000"), s.summary(u,p,2026,5).netMin()); }
 @Test void netoConRecuperoFijo(){ ok(); var i=MonthlyPlanItem.builder().profileId(p).type(MonthlyPlanItem.Type.EXPENSE).title("x").periodYear(2026).periodMonth(5).amount(new BigDecimal("100")).expectedRecoveryAmount(new BigDecimal("20")).build(); when(repo.findByProfileIdAndPeriodYearAndPeriodMonth(p,2026,5)).thenReturn(List.of(i)); assertEquals(new BigDecimal("-80"), s.summary(u,p,2026,5).netMin()); }
 @Test void cuentaSinCotizar(){ ok(); var i=MonthlyPlanItem.builder().profileId(p).type(MonthlyPlanItem.Type.TODO).title("x").periodYear(2026).periodMonth(5).build(); when(repo.findByProfileIdAndPeriodYearAndPeriodMonth(p,2026,5)).thenReturn(List.of(i)); assertEquals(1, s.summary(u,p,2026,5).unpricedCount()); }
 @Test void noConvierteSinDatos(){ ok(); var i=MonthlyPlanItem.builder().id(UUID.randomUUID()).profileId(p).type(MonthlyPlanItem.Type.EXPENSE).title("x").periodYear(2026).periodMonth(5).build(); when(repo.findByIdAndProfileId(i.getId(),p)).thenReturn(Optional.of(i)); assertThrows(BadRequestException.class,()->s.convert(u,p,i.getId())); }
 @Test void convierteIncome(){ ok(); var i=MonthlyPlanItem.builder().id(UUID.randomUUID()).profileId(p).type(MonthlyPlanItem.Type.INCOME).title("x").periodYear(2026).periodMonth(5).amount(new BigDecimal("10")).accountId(a).categoryId(c).build(); when(repo.findByIdAndProfileId(i.getId(),p)).thenReturn(Optional.of(i)); when(txRepo.save(any())).thenAnswer(x->{var t=x.getArgument(0, MoneyTransaction.class); t.setId(UUID.randomUUID()); return t;}); when(repo.save(any())).thenAnswer(x->x.getArgument(0)); when(matchRepo.findByProfileIdAndMonthlyPlanItemIdAndMoneyTransactionId(any(),any(),any())).thenReturn(Optional.empty()); assertEquals(MonthlyPlanItem.Status.COLLECTED,s.convert(u,p,i.getId()).status()); verify(matchRepo).save(any(MonthlyPlanTransactionMatch.class)); }
 @Test void convierteExpense(){ ok(); var i=MonthlyPlanItem.builder().id(UUID.randomUUID()).profileId(p).type(MonthlyPlanItem.Type.EXPENSE).title("x").expectedDate(LocalDate.of(2026,6,1)).periodYear(2026).periodMonth(5).amount(new BigDecimal("10")).accountId(a).categoryId(c).build(); when(repo.findByIdAndProfileId(i.getId(),p)).thenReturn(Optional.of(i)); when(txRepo.save(any())).thenAnswer(x->{var t=x.getArgument(0, MoneyTransaction.class); t.setId(UUID.randomUUID()); return t;}); when(repo.save(any())).thenAnswer(x->x.getArgument(0)); when(matchRepo.findByProfileIdAndMonthlyPlanItemIdAndMoneyTransactionId(any(),any(),any())).thenReturn(Optional.empty()); assertEquals(MonthlyPlanItem.Status.PAID,s.convert(u,p,i.getId()).status()); var tx=ArgumentCaptor.forClass(MoneyTransaction.class); verify(txRepo).save(tx.capture()); assertEquals(LocalDate.of(2026,6,1),tx.getValue().getRealDate()); assertEquals(LocalDate.of(2026,5,1),tx.getValue().getBudgetDate()); }
 @Test void convertNoDuplicaMatchSiYaExiste(){ ok(); var txId=UUID.randomUUID(); var i=MonthlyPlanItem.builder().id(UUID.randomUUID()).profileId(p).type(MonthlyPlanItem.Type.EXPENSE).title("x").periodYear(2026).periodMonth(5).amount(new BigDecimal("10")).accountId(a).categoryId(c).build(); when(repo.findByIdAndProfileId(i.getId(),p)).thenReturn(Optional.of(i)); when(txRepo.save(any())).thenAnswer(x->{var t=x.getArgument(0, MoneyTransaction.class); t.setId(txId); return t;}); when(repo.save(any())).thenAnswer(x->x.getArgument(0)); when(matchRepo.findByProfileIdAndMonthlyPlanItemIdAndMoneyTransactionId(p,i.getId(),txId)).thenReturn(Optional.of(MonthlyPlanTransactionMatch.builder().id(UUID.randomUUID()).build())); s.convert(u,p,i.getId()); verify(matchRepo,never()).save(any()); assertEquals(txId, i.getTransactionId()); }
 @Test void cancelledNoAfectaTotalesYPendings(){ ok(); var a1=MonthlyPlanItem.builder().profileId(p).type(MonthlyPlanItem.Type.EXPENSE).title("x").periodYear(2026).periodMonth(5).amount(new BigDecimal("100")).status(MonthlyPlanItem.Status.CANCELLED).priority(MonthlyPlanItem.Priority.IMPORTANT).createdAt(java.time.LocalDateTime.now()).build(); var a2=MonthlyPlanItem.builder().profileId(p).type(MonthlyPlanItem.Type.EXPENSE).title("y").periodYear(2026).periodMonth(5).amount(new BigDecimal("40")).status(MonthlyPlanItem.Status.DUE).priority(MonthlyPlanItem.Priority.IMPORTANT).createdAt(java.time.LocalDateTime.now()).build(); when(repo.findByProfileIdAndPeriodYearAndPeriodMonth(p,2026,5)).thenReturn(List.of(a1,a2)); var r=s.summary(u,p,2026,5); assertEquals(new BigDecimal("40"),r.pendingExpense()); assertEquals(new BigDecimal("-40"),r.netMin()); }
 @Test void noPermiteConversionDobleTodoOCancelled(){ ok(); var id=UUID.randomUUID(); var base=MonthlyPlanItem.builder().id(id).profileId(p).periodYear(2026).periodMonth(5).title("x").amount(new BigDecimal("10")).accountId(a).categoryId(c);
 when(repo.findByIdAndProfileId(id,p)).thenReturn(Optional.of(base.type(MonthlyPlanItem.Type.INCOME).transactionId(UUID.randomUUID()).build())); assertThrows(BadRequestException.class,()->s.convert(u,p,id));
 when(repo.findByIdAndProfileId(id,p)).thenReturn(Optional.of(base.type(MonthlyPlanItem.Type.TODO).transactionId(null).build())); assertThrows(BadRequestException.class,()->s.convert(u,p,id));
 when(repo.findByIdAndProfileId(id,p)).thenReturn(Optional.of(base.type(MonthlyPlanItem.Type.EXPENSE).status(MonthlyPlanItem.Status.CANCELLED).transactionId(null).build())); assertThrows(BadRequestException.class,()->s.convert(u,p,id)); }
 @Test void minMayorAMaxLanza(){ ok(); var req=new MonthlyPlanItemCreateRequest(MonthlyPlanItem.Type.EXPENSE,"x",null,null,2026,5,null,new BigDecimal("20"),new BigDecimal("10"),"ARS",null,null,null,null,null,null,null,null,c,a); assertThrows(BadRequestException.class,()->s.create(u,p,req)); }
 @Test void creacionDerivaPeriodoDesdeFechaEsperada(){ ok(); var req=new MonthlyPlanItemCreateRequest(MonthlyPlanItem.Type.EXPENSE,"x",null,LocalDate.of(2026,6,1),2026,5,new BigDecimal("10"),null,null,"ARS",null,null,null,null,null,null,null,null,c,a); when(repo.save(any())).thenAnswer(i->i.getArgument(0)); var res=s.create(u,p,req); assertEquals(2026,res.periodYear()); assertEquals(6,res.periodMonth()); }
 @Test void editarFechaEsperadaNoMuevePeriodoAutomaticamente(){ ok(); var id=UUID.randomUUID(); var item=MonthlyPlanItem.builder().id(id).profileId(p).type(MonthlyPlanItem.Type.EXPENSE).title("x").periodYear(2026).periodMonth(5).build(); when(repo.findByIdAndProfileId(id,p)).thenReturn(Optional.of(item)); when(repo.save(any())).thenAnswer(i->i.getArgument(0)); var res=s.update(u,p,id,updateReq(LocalDate.of(2026,6,1),null,null)); assertEquals(LocalDate.of(2026,6,1),res.expectedDate()); assertEquals(2026,res.periodYear()); assertEquals(5,res.periodMonth()); }
 @Test void validatorPermiteMesAnteriorActualYSiguiente(){ ok(); var id=UUID.randomUUID(); var item=MonthlyPlanItem.builder().id(id).profileId(p).type(MonthlyPlanItem.Type.EXPENSE).title("x").periodYear(2026).periodMonth(5).build(); when(repo.findByIdAndProfileId(id,p)).thenReturn(Optional.of(item)); when(repo.save(any())).thenAnswer(i->i.getArgument(0)); assertDoesNotThrow(()->s.update(u,p,id,updateReq(LocalDate.of(2026,4,30),null,null))); assertDoesNotThrow(()->s.update(u,p,id,updateReq(LocalDate.of(2026,5,15),null,null))); assertDoesNotThrow(()->s.update(u,p,id,updateReq(LocalDate.of(2026,6,1),null,null))); }
 @Test void validatorRechazaFechaDemasiadoAlejadaEnEdicion(){ ok(); var id=UUID.randomUUID(); var item=MonthlyPlanItem.builder().id(id).profileId(p).type(MonthlyPlanItem.Type.EXPENSE).title("x").periodYear(2026).periodMonth(5).build(); when(repo.findByIdAndProfileId(id,p)).thenReturn(Optional.of(item)); assertThrows(BadRequestException.class,()->s.update(u,p,id,updateReq(LocalDate.of(2026,7,1),null,null))); }
}
