import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Bar, BarChart, CartesianGrid, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { getMonthlyDashboard } from '../../api/dashboardApi';
import { AppLayout } from '../../components/layout/AppLayout';
import type { DashboardSummary, FinancialRiskLevel } from '../../domain/types';
import { formatMoney } from '../../domain/formatters';
const riskLabels:Record<FinancialRiskLevel,string>={OK:'Correcto',WATCH:'Atención',RISK:'Riesgo',CRITICAL:'Crítico'};
const riskClass:Record<FinancialRiskLevel,string>={OK:'badge badge-ok',WATCH:'badge badge-watch',RISK:'badge badge-risk',CRITICAL:'badge badge-critical'};
export function DashboardPage(){const {profileId=''}=useParams(); const d=new Date(); const [year,setYear]=useState(d.getFullYear()); const [month,setMonth]=useState(d.getMonth()+1);
  const q=useQuery<DashboardSummary>({queryKey:['dashboard',profileId,year,month],queryFn:()=>getMonthlyDashboard(profileId,year,month),enabled:Boolean(profileId)}); const s=q.data;
  const p=s?.planningSummary??{totalIncomeMin:0,totalIncomeMax:0,totalExpenseMin:0,totalExpenseMax:0,totalRecoveryMin:0,totalRecoveryMax:0,projectedNetMin:0,projectedNetMax:0,pendingIncome:0,pendingExpense:0,unpricedCount:0,dueNext7DaysCount:0,plannedItemsCount:0,cancelledItemsCount:0,convertedItemsCount:0};
  const o=s?.operationalSummary??{confirmedIncome:0,confirmedExpenses:0,confirmedSavings:0,confirmedBalance:0,projectedNetMin:0,projectedNetMax:0,deltaProjectedMinVsConfirmed:0,deltaProjectedMaxVsConfirmed:0,pendingIncome:0,pendingExpense:0,expectedRecoveriesMin:0,expectedRecoveriesMax:0,unpricedCount:0,dueNext7DaysCount:0,financialRiskLevel:'OK' as FinancialRiskLevel,alerts:[]};
  return <AppLayout><div className='card'><h1>Panel mensual</h1><div className='form-row'><label>Año<input className='input' type='number' value={year} onChange={e=>setYear(Number(e.target.value))}/></label><label>Mes<input className='input' type='number' min={1} max={12} value={month} onChange={e=>setMonth(Number(e.target.value))}/></label></div><p><Link to={`/profiles/${profileId}/planning`}>Ir a planificación</Link>{' · '}<Link to={`/profiles/${profileId}/transactions`}>Cargar movimiento</Link></p>
  {q.isLoading&&<p className='empty-state'>Cargando información financiera...</p>}{q.isError&&<p className='error-box'>No se pudo cargar el panel mensual.</p>}
  {s&&<><h3>Estado operativo del mes</h3><div className='grid'>{[['Neto proyectado min/max',`${formatMoney(o.projectedNetMin)} / ${formatMoney(o.projectedNetMax)}`],['Saldo confirmado',formatMoney(o.confirmedBalance)],['Pendiente de cobro',formatMoney(o.pendingIncome)],['Pendiente de pago',formatMoney(o.pendingExpense)],['Recuperos esperados',`${formatMoney(o.expectedRecoveriesMin)} / ${formatMoney(o.expectedRecoveriesMax)}`]].map(x=><div key={x[0]} className='card'><b>{x[0]}</b><div className='kpi-value'>{x[1]}</div></div>)}<div className='card'><b>Riesgo financiero</b><div className={riskClass[o.financialRiskLevel]}>{riskLabels[o.financialRiskLevel]}</div></div></div>
  <div className='card'><h3>Alertas operativas</h3>{o.alerts.length===0?<p>Sin alertas operativas para este período.</p>:<ul>{o.alerts.map(a=><li key={a}>{a}</li>)}</ul>}</div>
  <div className='grid'><div className='card'><h3>Confirmado</h3><p>Ingresos: {formatMoney(o.confirmedIncome)}</p><p>Egresos: {formatMoney(o.confirmedExpenses)}</p><p>Ahorro: {formatMoney(o.confirmedSavings)}</p><p>Saldo: {formatMoney(o.confirmedBalance)}</p></div><div className='card'><h3>Proyectado</h3><p>Ingresos: {formatMoney(p.totalIncomeMin)} / {formatMoney(p.totalIncomeMax)}</p><p>Egresos: {formatMoney(p.totalExpenseMin)} / {formatMoney(p.totalExpenseMax)}</p><p>Recuperos: {formatMoney(p.totalRecoveryMin)} / {formatMoney(p.totalRecoveryMax)}</p><p>Neto: {formatMoney(p.projectedNetMin)} / {formatMoney(p.projectedNetMax)}</p><p>Diferencia vs saldo: {formatMoney(o.deltaProjectedMinVsConfirmed)} / {formatMoney(o.deltaProjectedMaxVsConfirmed)}</p></div></div>
  <div className='grid'><div className='card'><b>Sin cotizar</b><div>{p.unpricedCount}</div></div><div className='card'><b>Próximos 7 días</b><div>{p.dueNext7DaysCount}</div></div><div className='card'><b>Items convertidos</b><div>{p.convertedItemsCount}</div></div><div className='card'><b>Items cancelados</b><div>{p.cancelledItemsCount}</div></div></div>
  <div className='card'><h3>Regla 50/30/20</h3><p>Gastos fijos: {s.fiftyThirtyTwenty?.fixedPercent ?? 0}% | Gastos variables: {s.fiftyThirtyTwenty?.variablePercent ?? 0}% | Ahorro: {s.fiftyThirtyTwenty?.savingPercent ?? 0}%</p></div>
  <div className='grid'><div className='card chart-card'><h3>Distribución del mes</h3><ResponsiveContainer width='100%' height={220}><PieChart><Pie data={[{name:'Gastos fijos',value:Number(s.fixedExpenses??0)},{name:'Gastos variables',value:Number(s.variableExpenses??0)},{name:'Ahorro',value:Number(s.monthlyBalance?.savings??0)}]} dataKey='value' nameKey='name' outerRadius={90}/><Tooltip formatter={(v)=>formatMoney(v as number)} /></PieChart></ResponsiveContainer></div>
  <div className='card chart-card'><h3>Presupuesto vs real</h3><ResponsiveContainer width='100%' height={220}><BarChart data={s.categoryBreakdown.map(i=>({categoria:i.categoryName,real:Number(i.totalAmount??0)}))}><CartesianGrid strokeDasharray='3 3'/><XAxis dataKey='categoria' hide/><YAxis/><Tooltip formatter={(v)=>formatMoney(v as number)} /><Bar dataKey='real' fill='#0f766e' /></BarChart></ResponsiveContainer></div></div>
  </>}
  </div></AppLayout>; }
