package com.hogaria.controller;
import com.hogaria.dto.PlanningDtos.*;import com.hogaria.security.CurrentUserResolver;import com.hogaria.service.*;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;import java.time.*;import java.util.*;
@RestController @RequestMapping("/api")
public class PlanningController {
private final CurrentUserResolver cu; private final FinancialGoalService gs; private final HabitService hs; private final InflationService is;
public PlanningController(CurrentUserResolver cu,FinancialGoalService gs,HabitService hs,InflationService is){this.cu=cu;this.gs=gs;this.hs=hs;this.is=is;}
@GetMapping("/profiles/{profileId}/goals") public List<FinancialGoalResponse> goals(@RequestHeader(value = "X-User-Id", required = false) String h,@PathVariable UUID profileId){return gs.list(cu.parse(h),profileId);} 
@PostMapping("/profiles/{profileId}/goals") public FinancialGoalResponse createGoal(@RequestHeader(value = "X-User-Id", required = false) String h,@PathVariable UUID profileId,@Valid @RequestBody FinancialGoalCreateRequest r){return gs.create(cu.parse(h),profileId,r);} 
@DeleteMapping("/profiles/{profileId}/goals/{goalId}") public void delGoal(@RequestHeader(value = "X-User-Id", required = false) String h,@PathVariable UUID profileId,@PathVariable UUID goalId){gs.delete(cu.parse(h),profileId,goalId);} 
@PostMapping("/profiles/{profileId}/goals/emergency-fund") public FinancialGoalResponse emergency(@RequestHeader(value = "X-User-Id", required = false) String h,@PathVariable UUID profileId,@Valid @RequestBody EmergencyFundRequest r){return gs.emergencyFund(cu.parse(h),profileId,r.coverageMonths());}
@GetMapping("/profiles/{profileId}/habits") public List<HabitResponse> habits(@RequestHeader(value = "X-User-Id", required = false) String h,@PathVariable UUID profileId){return hs.list(cu.parse(h),profileId);} 
@PostMapping("/profiles/{profileId}/habits") public HabitResponse createHabit(@RequestHeader(value = "X-User-Id", required = false) String h,@PathVariable UUID profileId,@Valid @RequestBody HabitCreateRequest r){return hs.create(cu.parse(h),profileId,r);} 
@PutMapping("/profiles/{profileId}/habits/{habitId}/checkins/{date}") public HabitCheckinResponse check(@RequestHeader(value = "X-User-Id", required = false) String h,@PathVariable UUID profileId,@PathVariable UUID habitId,@PathVariable LocalDate date,@RequestBody HabitCheckinRequest r){return hs.check(cu.parse(h),profileId,habitId,date,r);} 
@GetMapping("/inflation") public List<InflationIndexResponse> listInfl(@RequestParam Integer year){return is.list(year);} @PostMapping("/inflation") public InflationIndexResponse createInfl(@Valid @RequestBody InflationIndexCreateRequest r){return is.create(r);} @GetMapping("/inflation/accumulated") public InflationAccumulatedResponse acc(@RequestParam int fromYear,@RequestParam int fromMonth,@RequestParam int toYear,@RequestParam int toMonth){return is.acc(fromYear,fromMonth,toYear,toMonth);} }
