import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { commitBudgetExcelImport, previewBudgetExcelImport } from '../../api/importsApi';
import { getApiErrorMessage } from '../../api/http';
import { AppLayout } from '../../components/layout/AppLayout';
import { importRowStatusLabels, importTargetEntityLabels, labelOrValue, profileTypeLabels } from '../../domain/financeLabels';
import { formatMoney, formatMonth, formatNumber, normalizeOptionalText } from '../../domain/formatters';
import type { BudgetExcelImportCommitRequest, BudgetExcelImportPreviewResponse } from '../../domain/types';

const defaultOptions: BudgetExcelImportCommitRequest = { createCategories: true, createAccounts: true, createBudgets: true, createTransactions: true, createGoals: true, createHabits: true, createInflation: true, updateExisting: true, ignoreInvalidRows: true, year: new Date().getFullYear(), currency: 'ARS', profileType: 'PERSONAL' };

export function BudgetExcelImportPage() { const { profileId = '' } = useParams(); const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<BudgetExcelImportPreviewResponse | null>(null); const [options, setOptions] = useState(defaultOptions); const [loading, setLoading] = useState(false); const [msg, setMsg] = useState('');
  const analyze = async () => { if (!file) return; setLoading(true); setMsg(''); try { setPreview(await previewBudgetExcelImport(profileId, file)); } catch (e) { setMsg(getApiErrorMessage(e)); } finally { setLoading(false); } };
  const commit = async () => { if (!preview) return; setLoading(true); setMsg(''); try { const r = await commitBudgetExcelImport(profileId, preview.batchId, options); setMsg(`Importación finalizada: ${r.status}.`); } catch (e) { setMsg(getApiErrorMessage(e)); } finally { setLoading(false); } };
  return <AppLayout><section className='card'><h1>Carga guiada de Excel</h1><ol><li>Seleccionar archivo</li><li>Analizar Excel</li><li>Revisar hojas detectadas/faltantes</li><li>Elegir opciones de importación</li><li>Ver filas detectadas</li><li>Confirmar importación</li><li>Ver resultado y links</li></ol>
    <input className='input' type='file' accept='.xlsx' onChange={(e) => setFile(e.target.files?.[0] ?? null)} /><button className='button-primary' onClick={analyze} disabled={!file || loading}>Analizar Excel</button>
    {preview && <><p>Hojas detectadas: {preview.detectedSheets.join(', ') || '-'}</p><p>Hojas faltantes: {preview.missingSheets.join(', ') || 'Ninguna'}</p>
      <div className='form-row'><label><input type='checkbox' checked={options.createCategories} onChange={e => setOptions({ ...options, createCategories: e.target.checked })} /> Crear categorías</label><label><input type='checkbox' checked={options.createAccounts} onChange={e => setOptions({ ...options, createAccounts: e.target.checked })} /> Crear cuentas</label><label><input type='checkbox' checked={options.createBudgets} onChange={e => setOptions({ ...options, createBudgets: e.target.checked })} /> Crear presupuestos</label><label><input type='checkbox' checked={options.createTransactions} onChange={e => setOptions({ ...options, createTransactions: e.target.checked })} /> Crear movimientos</label><label><input type='checkbox' checked={options.createGoals} onChange={e => setOptions({ ...options, createGoals: e.target.checked })} /> Crear objetivos</label><label><input type='checkbox' checked={options.createHabits} onChange={e => setOptions({ ...options, createHabits: e.target.checked })} /> Crear hábitos</label><label><input type='checkbox' checked={options.createInflation} onChange={e => setOptions({ ...options, createInflation: e.target.checked })} /> Crear inflación</label></div>
      <div className='form-row'><label>Año <input className='input' type='number' value={options.year} onChange={e => setOptions({ ...options, year: Number(e.target.value) })} /></label><label>Moneda <input className='input' value={options.currency} onChange={e => setOptions({ ...options, currency: e.target.value.toUpperCase() })} /></label><label>Tipo de perfil<select className='select' value={options.profileType} onChange={e => setOptions({ ...options, profileType: e.target.value as BudgetExcelImportCommitRequest['profileType'] })}><option value='PERSONAL'>{profileTypeLabels.PERSONAL}</option><option value='FAMILY'>{profileTypeLabels.FAMILY}</option><option value='BUSINESS'>{profileTypeLabels.BUSINESS}</option></select></label></div>
      <button className='button-secondary' onClick={commit} disabled={loading}>Confirmar importación</button>
      <table className='table'><thead><tr><th>Hoja</th><th>Fila</th><th>Concepto</th><th>Mes</th><th>Monto</th><th>Entidad</th><th>Estado</th></tr></thead><tbody>{preview.rows.slice(0, 200).map((r) => <tr key={r.id}><td>{normalizeOptionalText(r.sheetName)}</td><td>{r.rowNumber ? formatNumber(r.rowNumber) : '-'}</td><td>{normalizeOptionalText(r.concept)}</td><td>{formatMonth(r.month ?? undefined)}</td><td>{formatMoney(r.amount)}</td><td>{labelOrValue(importTargetEntityLabels, r.targetEntity ?? 'UNKNOWN')}</td><td>{labelOrValue(importRowStatusLabels, r.status)}</td></tr>)}</tbody></table>
      <p><Link to={`/profiles/${profileId}/dashboard`}>Ir al panel mensual</Link></p></>}
    {msg && <p className={msg.toLowerCase().includes('error') ? 'error-box' : 'empty-state'}>{msg}</p>}</section></AppLayout>; }
