import { http } from './http';
export const createBudgetYear = (profileId, p) => http.post(`/api/profiles/${profileId}/budgets`, p).then(r => r.data);
export const listBudgetYears = (profileId) => http.get(`/api/profiles/${profileId}/budgets`).then(r => r.data);
export const getBudgetYear = (profileId, year) => http.get(`/api/profiles/${profileId}/budgets/${year}`).then(r => r.data);
export const updateBudgetYear = (profileId, year, p) => http.put(`/api/profiles/${profileId}/budgets/${year}`, p).then(r => r.data);
export const createBudgetMonth = (profileId, year, p) => http.post(`/api/profiles/${profileId}/budgets/${year}/months`, p).then(r => r.data);
export const getBudgetMonth = (profileId, year, month) => http.get(`/api/profiles/${profileId}/budgets/${year}/months/${month}`).then(r => r.data);
export const updateBudgetMonth = (id, p) => http.put(`/api/budget-months/${id}`, p).then(r => r.data);
export const upsertBudgetCategoryItem = (id, p) => http.put(`/api/budget-months/${id}/items`, p).then(r => r.data);
export const deleteBudgetCategoryItem = (id) => http.delete(`/api/budget-category-items/${id}`).then(r => r.data);
export const getBudgetComparison = (profileId, year, month) => http.get(`/api/profiles/${profileId}/budgets/${year}/months/${month}/comparison`).then(r => r.data);
