package com.hogaria.dto;
import com.hogaria.entity.Category;import java.math.BigDecimal;import java.util.*;
public class DashboardDtos {
  public record CategorySummaryResponse(UUID categoryId, String categoryName, Category.Type categoryType, BigDecimal totalAmount, BigDecimal percentOfIncome, long movementCount) {}
  public record FiftyThirtyTwentyResponse(BigDecimal fixedPercent, BigDecimal variablePercent, BigDecimal savingPercent) {}
  public record MonthlyBalanceResponse(BigDecimal totalIncome, BigDecimal totalExpenses, BigDecimal savings, BigDecimal balance) {}
  public record BudgetSummaryResponse(BigDecimal totalBudget,BigDecimal totalReal,BigDecimal totalDifference,long exceededCount,long warningCount){}
  public record PlanningDashboardSummaryResponse(BigDecimal totalIncomeMin, BigDecimal totalIncomeMax, BigDecimal totalExpenseMin, BigDecimal totalExpenseMax, BigDecimal totalRecoveryMin, BigDecimal totalRecoveryMax, BigDecimal projectedNetMin, BigDecimal projectedNetMax, BigDecimal pendingIncome, BigDecimal pendingExpense, int unpricedCount, int dueNext7DaysCount, int plannedItemsCount, int cancelledItemsCount, int convertedItemsCount) {}
  public record DashboardOperationalSummaryResponse(BigDecimal confirmedIncome, BigDecimal confirmedExpenses, BigDecimal confirmedSavings, BigDecimal confirmedBalance, BigDecimal projectedNetMin, BigDecimal projectedNetMax, BigDecimal deltaProjectedMinVsConfirmed, BigDecimal deltaProjectedMaxVsConfirmed, BigDecimal pendingIncome, BigDecimal pendingExpense, BigDecimal expectedRecoveriesMin, BigDecimal expectedRecoveriesMax, int unpricedCount, int dueNext7DaysCount, String financialRiskLevel, List<String> alerts, BigDecimal consumptionExpense, BigDecimal recoverableOutflow, BigDecimal principalRecovery, BigDecimal operationalBalanceExcludingRecoverables, BigDecimal netCashFlowIncludingRecoverables) {}

  public record MonthlyCashFlowSummaryResponse(BigDecimal grossCashOutflow, BigDecimal consumptionExpense, BigDecimal fixedExpense, BigDecimal variableExpense, BigDecimal debtOutflow, BigDecimal savingOutflow, BigDecimal investmentOutflow, BigDecimal recoverableOutflow, BigDecimal principalRecovered, BigDecimal refundsOrReimbursements, BigDecimal earnedIncome, BigDecimal interestIncome, BigDecimal totalIncome, BigDecimal netCashFlow, BigDecimal economicNetExpense, BigDecimal internalTransfers, BigDecimal externalTransfers, BigDecimal neutralAdjustments, BigDecimal unknownOutflow, List<String> alerts, BigDecimal principalRecovery, BigDecimal operationalBalanceExcludingRecoverables, BigDecimal netCashFlowIncludingRecoverables) {}
  public record DashboardSummaryResponse(MonthlyBalanceResponse monthlyBalance, FiftyThirtyTwentyResponse fiftyThirtyTwenty, BigDecimal fixedExpenses, BigDecimal variableExpenses, String financialHealth, List<CategorySummaryResponse> categoryBreakdown,BudgetSummaryResponse budgetSummary, PlanningDashboardSummaryResponse planningSummary, DashboardOperationalSummaryResponse operationalSummary, MonthlyCashFlowSummaryResponse monthlyCashFlowSummary) {}
}
