CREATE TABLE monthly_plan_item (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    profile_id UUID NOT NULL REFERENCES financial_profile(id),
    category_id UUID REFERENCES category(id),
    account_id UUID REFERENCES account(id),
    type VARCHAR(30) NOT NULL CHECK (type IN ('INCOME','EXPENSE','SAVING','DEBT','TRANSFER','RECOVERY','TODO')),
    title VARCHAR(160) NOT NULL,
    description VARCHAR(500),
    expected_date DATE,
    period_year INT NOT NULL CHECK (period_year BETWEEN 2000 AND 2100),
    period_month INT NOT NULL CHECK (period_month BETWEEN 1 AND 12),
    amount NUMERIC(19,2),
    min_amount NUMERIC(19,2),
    max_amount NUMERIC(19,2),
    currency VARCHAR(3) NOT NULL DEFAULT 'ARS',
    expected_recovery_amount NUMERIC(19,2),
    expected_recovery_percent NUMERIC(5,2),
    counterparty VARCHAR(120),
    installment_number INT,
    installment_total INT,
    priority VARCHAR(20) NOT NULL DEFAULT 'IMPORTANT' CHECK (priority IN ('ESSENTIAL','IMPORTANT','OPTIONAL')),
    status VARCHAR(30) NOT NULL DEFAULT 'ESTIMATED' CHECK (status IN ('DRAFT','ESTIMATED','SCHEDULED','DUE','PAID','COLLECTED','CANCELLED')),
    source VARCHAR(30) NOT NULL DEFAULT 'MANUAL' CHECK (source IN ('MANUAL','IMPORT','QUICK_CAPTURE','SYSTEM')),
    transaction_id UUID REFERENCES money_transaction(id),
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    CHECK (amount IS NULL OR amount >= 0),
    CHECK (min_amount IS NULL OR min_amount >= 0),
    CHECK (max_amount IS NULL OR max_amount >= 0),
    CHECK (expected_recovery_amount IS NULL OR expected_recovery_amount >= 0),
    CHECK (expected_recovery_percent IS NULL OR (expected_recovery_percent >= 0 AND expected_recovery_percent <= 100)),
    CHECK (installment_number IS NULL OR installment_number > 0),
    CHECK (installment_total IS NULL OR installment_total > 0),
    CHECK (installment_number IS NULL OR installment_total IS NULL OR installment_number <= installment_total)
);
CREATE INDEX idx_monthly_plan_item_profile_period ON monthly_plan_item(profile_id, period_year, period_month);
