import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useMemo, useState } from 'react';
import { labelOrValue, monthlyPlanPriorityLabels, monthlyPlanStatusLabels, monthlyPlanTypeLabels } from '../../../domain/financeLabels';
import { canConvertPlanItem, formatPlanNet } from '../planningUtils';
import { StatusBadge } from '../../../components/ui/StatusBadge';
export function MonthlyPlanItemsTable({ items, onConvert, onCancel, onDelete }) {
    const [statusFilter, setStatusFilter] = useState('ALL');
    const [typeFilter, setTypeFilter] = useState('ALL');
    const [sortBy, setSortBy] = useState('DATE');
    const filtered = useMemo(() => items.filter((i) => (statusFilter === 'ALL' || (statusFilter === 'PENDING' ? ['ESTIMATED', 'PLANNED'].includes(i.status) : statusFilter === 'DONE' ? ['PAID', 'RECEIVED'].includes(i.status) : i.status === 'CANCELLED')) && (typeFilter === 'ALL' || i.type === typeFilter)).sort((a, b) => sortBy === 'DATE' ? (a.expectedDate ?? '').localeCompare(b.expectedDate ?? '') : sortBy === 'PRIORITY' ? a.priority.localeCompare(b.priority) : (b.netMax ?? 0) - (a.netMax ?? 0)), [items, statusFilter, typeFilter, sortBy]);
    return _jsxs("section", { className: 'card', children: [_jsx("h3", { className: 'section-title', children: "Items planificados" }), _jsxs("div", { className: 'form-row', children: [_jsxs("select", { className: 'select', value: statusFilter, onChange: (e) => setStatusFilter(e.target.value), children: [_jsx("option", { value: 'ALL', children: "Todos" }), _jsx("option", { value: 'PENDING', children: "Pendientes" }), _jsx("option", { value: 'DONE', children: "Pagados-Cobrados" }), _jsx("option", { value: 'CANCELLED', children: "Cancelados" })] }), _jsxs("select", { className: 'select', value: typeFilter, onChange: (e) => setTypeFilter(e.target.value), children: [_jsx("option", { value: 'ALL', children: "Todos" }), _jsx("option", { value: 'INCOME', children: "Ingresos" }), _jsx("option", { value: 'EXPENSE', children: "Egresos" }), _jsx("option", { value: 'RECOVERY', children: "Recuperos" }), _jsx("option", { value: 'TODO', children: "TODO" })] }), _jsxs("select", { className: 'select', value: sortBy, onChange: (e) => setSortBy(e.target.value), children: [_jsx("option", { value: 'DATE', children: "Fecha" }), _jsx("option", { value: 'PRIORITY', children: "Prioridad" }), _jsx("option", { value: 'AMOUNT', children: "Monto" })] })] }), _jsxs("table", { className: 'table', children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { children: "Fecha" }), _jsx("th", { children: "T\u00EDtulo" }), _jsx("th", { children: "Tipo" }), _jsx("th", { children: "Neto" }), _jsx("th", { children: "Estado" }), _jsx("th", { children: "Prioridad" }), _jsx("th", { children: "Acciones" })] }) }), _jsx("tbody", { children: filtered.map((i) => { const canConvert = canConvertPlanItem(i); return _jsxs("tr", { children: [_jsx("td", { children: i.expectedDate ?? '-' }), _jsxs("td", { children: [i.title, " ", i.transactionId && _jsx("span", { className: 'compact-muted', children: "\u00B7 Convertido" })] }), _jsx("td", { children: labelOrValue(monthlyPlanTypeLabels, i.type) }), _jsx("td", { children: formatPlanNet(i) }), _jsx("td", { children: _jsx(StatusBadge, { label: labelOrValue(monthlyPlanStatusLabels, i.status) }) }), _jsx("td", { children: _jsx(StatusBadge, { label: labelOrValue(monthlyPlanPriorityLabels, i.priority) }) }), _jsxs("td", { className: 'table-actions', children: [_jsx("button", { className: 'button-primary', disabled: !canConvert, title: canConvert ? '' : 'Requiere monto exacto, cuenta y categoría.', onClick: () => onConvert(i.id), children: "Convertir" }), _jsx("button", { className: 'button-secondary', onClick: () => onCancel(i.id), children: "Cancelar" }), _jsx("button", { className: 'button-danger', onClick: () => onDelete(i.id), children: "Eliminar" })] })] }, i.id); }) })] })] });
}
