import { useMemo, useState } from 'react';
import { labelOrValue, monthlyPlanPriorityLabels, monthlyPlanStatusLabels, monthlyPlanTypeLabels } from '../../../domain/financeLabels';
import type { MonthlyPlanItem } from '../../../domain/types';
import { canConvertPlanItem, formatPlanNet } from '../planningUtils';
import { StatusBadge } from '../../../components/ui/StatusBadge';

type Props = { items: MonthlyPlanItem[]; onConvert: (id: string) => void; onCancel: (id: string) => void; onDelete: (id: string) => void };
export function MonthlyPlanItemsTable({ items, onConvert, onCancel, onDelete }: Props) {
  const [statusFilter, setStatusFilter] = useState('ALL');
  const [typeFilter, setTypeFilter] = useState('ALL');
  const [sortBy, setSortBy] = useState<'DATE' | 'PRIORITY' | 'AMOUNT'>('DATE');
  const filtered = useMemo(() => items.filter((i) => (statusFilter === 'ALL' || (statusFilter === 'PENDING' ? ['ESTIMATED', 'PLANNED'].includes(i.status) : statusFilter === 'DONE' ? ['PAID', 'RECEIVED'].includes(i.status) : i.status === 'CANCELLED')) && (typeFilter === 'ALL' || i.type === typeFilter)).sort((a, b) => sortBy === 'DATE' ? (a.expectedDate ?? '').localeCompare(b.expectedDate ?? '') : sortBy === 'PRIORITY' ? a.priority.localeCompare(b.priority) : (b.netMax ?? 0) - (a.netMax ?? 0)), [items, statusFilter, typeFilter, sortBy]);
  return <section className='card'><h3 className='section-title'>Items planificados</h3><div className='form-row'><select className='select' value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)}><option value='ALL'>Todos</option><option value='PENDING'>Pendientes</option><option value='DONE'>Pagados-Cobrados</option><option value='CANCELLED'>Cancelados</option></select><select className='select' value={typeFilter} onChange={(e) => setTypeFilter(e.target.value)}><option value='ALL'>Todos</option><option value='INCOME'>Ingresos</option><option value='EXPENSE'>Egresos</option><option value='RECOVERY'>Recuperos</option><option value='TODO'>TODO</option></select><select className='select' value={sortBy} onChange={(e) => setSortBy(e.target.value as 'DATE'|'PRIORITY'|'AMOUNT')}><option value='DATE'>Fecha</option><option value='PRIORITY'>Prioridad</option><option value='AMOUNT'>Monto</option></select></div><table className='table'><thead><tr><th>Fecha</th><th>Título</th><th>Tipo</th><th>Neto</th><th>Estado</th><th>Prioridad</th><th>Acciones</th></tr></thead><tbody>{filtered.map((i) => { const canConvert = canConvertPlanItem(i); return <tr key={i.id}><td>{i.expectedDate ?? '-'}</td><td>{i.title} {i.transactionId && <span className='compact-muted'>· Convertido</span>}</td><td>{labelOrValue(monthlyPlanTypeLabels, i.type)}</td><td>{formatPlanNet(i)}</td><td><StatusBadge label={labelOrValue(monthlyPlanStatusLabels, i.status)} /></td><td><StatusBadge label={labelOrValue(monthlyPlanPriorityLabels, i.priority)} /></td><td className='table-actions'><button className='button-primary' disabled={!canConvert} title={canConvert ? '' : 'Requiere monto exacto, cuenta y categoría.'} onClick={() => onConvert(i.id)}>Convertir</button><button className='button-secondary' onClick={() => onCancel(i.id)}>Cancelar</button><button className='button-danger' onClick={() => onDelete(i.id)}>Eliminar</button></td></tr>; })}</tbody></table></section>;
}
