import { useState } from 'react';
import { monthlyPlanPriorityOptions, monthlyPlanStatusOptions, monthlyPlanTypeOptions } from '../../../domain/financeOptions';
import type { Account, Category, MonthlyPlanItem, MonthlyPlanItemCreatePayload, PlanningSuggestionResponse, QuickCapturePreviewResponse } from '../../../domain/types';
import { confidenceMeta, formatPlanAmount, formatPlanRecovery } from '../planningUtils';
import { getMonthlyPlanSuggestions } from '../../../api/monthlyPlanSuggestionsApi';

type Props = { profileId: string; preview: QuickCapturePreviewResponse; form: MonthlyPlanItemCreatePayload; setForm: (next: MonthlyPlanItemCreatePayload) => void; accounts: Account[]; categories: Category[]; onConfirm: () => void };
const confLabel = (c?: string) => c === 'HIGH' ? 'Alta' : c === 'MEDIUM' ? 'Media' : c === 'LOW' ? 'Baja' : 'Sin confianza';
export function QuickCapturePreviewForm({ profileId, preview, form, setForm, accounts, categories, onConfirm }: Props) { const confidence = confidenceMeta(preview.confidence); const [sugg, setSugg] = useState<PlanningSuggestionResponse | null>(null);
  const load = async () => setSugg(await getMonthlyPlanSuggestions(profileId, { type: form.type, title: form.title, counterparty: form.counterparty ?? null, amount: form.amount ?? null, minAmount: form.minAmount ?? null, maxAmount: form.maxAmount ?? null, expectedRecoveryAmount: form.expectedRecoveryAmount ?? null, expectedRecoveryPercent: form.expectedRecoveryPercent ?? null }));
  const apply = () => { if(!sugg) return; setForm({ ...form, accountId: sugg.accountSuggestion?.id ?? form.accountId ?? null, categoryId: sugg.categorySuggestion?.id ?? form.categoryId ?? null }); };
  return <div className='page-stack'><p><b>Confianza:</b> <span className={`badge ${confidence.className}`}>{confidence.label}</span></p>{preview.warnings.length > 0 && <ul>{preview.warnings.map((w, i) => <li key={i}>{w}</li>)}</ul>}<div className='form-grid'><select className='select' value={form.type} onChange={e => setForm({ ...form, type: e.target.value as MonthlyPlanItem['type'] })}>{monthlyPlanTypeOptions.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}</select><input className='input' value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} placeholder='Título' /><select className='select' value={form.priority} onChange={e => setForm({ ...form, priority: e.target.value as MonthlyPlanItem['priority'] })}>{monthlyPlanPriorityOptions.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}</select><select className='select' value={form.status} onChange={e => setForm({ ...form, status: e.target.value as MonthlyPlanItem['status'] })}>{monthlyPlanStatusOptions.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}</select><select className='select' value={form.accountId ?? ''} onChange={e => setForm({ ...form, accountId: e.target.value || null })}><option value=''>Cuenta opcional</option>{accounts.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select><select className='select' value={form.categoryId ?? ''} onChange={e => setForm({ ...form, categoryId: e.target.value || null })}><option value=''>Categoría opcional</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></div>
  <div className='table-actions'><button className='button-secondary' onClick={()=>void load()}>Pedir sugerencias</button>{sugg && <button className='button-primary' onClick={apply}>Aplicar sugerencias</button>}</div>
  {sugg && <div><p><b>Sugerencias</b></p>{sugg.confidence==='NONE'?<p>Sin sugerencias confiables por ahora.</p>:<><p>Categoría sugerida: {sugg.categorySuggestion?.name ?? '-'} — confianza {confLabel(sugg.categorySuggestion?.confidence)}</p><p>Cuenta sugerida: {sugg.accountSuggestion?.name ?? '-'} — confianza {confLabel(sugg.accountSuggestion?.confidence)}</p><ul>{sugg.reasons.map((r,idx)=><li key={idx}>{r}</li>)}</ul></>}</div>}
  <p>Monto detectado: {formatPlanAmount(form as MonthlyPlanItem)}</p><p>Recupero detectado: {formatPlanRecovery(form as MonthlyPlanItem)}</p><button className='button-primary' onClick={onConfirm} disabled={!form.title.trim()}>Confirmar y crear</button></div>; }
