import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { listAccounts } from '../../api/accountsApi';
import { listCategories } from '../../api/categoriesApi';
import { getApiErrorMessage } from '../../api/http';
import { commitMonthlyPlanQuickCapture, previewMonthlyPlanQuickCapture } from '../../api/monthlyPlanQuickCaptureApi';
import { convertMonthlyPlanItemToTransaction, createMonthlyPlanItem, deleteMonthlyPlanItem, getMonthlyPlan, updateMonthlyPlanItem } from '../../api/monthlyPlanningApi';
import { AppLayout } from '../../components/layout/AppLayout';
import { MonthSelector } from '../../components/ui/MonthSelector';
import { MonthlyPlanItemsTable } from './components/MonthlyPlanItemsTable';
import { MonthlyPlanningChecklist } from './components/MonthlyPlanningChecklist';
import { MonthlyPlanningGuide } from './components/MonthlyPlanningGuide';
import { PlanningSummaryCards } from './components/PlanningSummaryCards';
import { QuickCapturePanel } from './components/QuickCapturePanel';
import { QuickCapturePreviewForm } from './components/QuickCapturePreviewForm';
import { StructuredPlanItemForm } from './components/StructuredPlanItemForm';
export function MonthlyPlanningPage() {
    const { profileId = '' } = useParams();
    const qc = useQueryClient();
    const d = new Date();
    const [year, setYear] = useState(d.getFullYear());
    const [month, setMonth] = useState(d.getMonth() + 1);
    const [tableFilter, setTableFilter] = useState('ALL');
    const [quickText, setQuickText] = useState('');
    const [quickPreview, setQuickPreview] = useState(null);
    const [quickForm, setQuickForm] = useState(null);
    const [quickError, setQuickError] = useState('');
    const [form, setForm] = useState({ type: 'EXPENSE', title: '', periodYear: year, periodMonth: month, priority: 'IMPORTANT', status: 'ESTIMATED', currency: 'ARS' });
    const inv = () => { qc.invalidateQueries({ queryKey: ['planning', profileId, year, month] }); qc.invalidateQueries({ queryKey: ['dashboard', profileId, year, month] }); qc.invalidateQueries({ queryKey: ['tx', profileId, year, month] }); };
    const q = useQuery({ queryKey: ['planning', profileId, year, month], queryFn: () => getMonthlyPlan(profileId, year, month), enabled: Boolean(profileId) });
    const aq = useQuery({ queryKey: ['accounts', profileId], queryFn: () => listAccounts(profileId), enabled: Boolean(profileId) });
    const cq = useQuery({ queryKey: ['categories', profileId], queryFn: () => listCategories(profileId, true), enabled: Boolean(profileId) });
    const create = useMutation({ mutationFn: () => createMonthlyPlanItem(profileId, { ...form, periodYear: year, periodMonth: month }), onSuccess: () => { setForm({ ...form, title: '' }); inv(); } });
    const del = useMutation({ mutationFn: (id) => deleteMonthlyPlanItem(profileId, id), onSuccess: inv });
    const conv = useMutation({ mutationFn: (id) => convertMonthlyPlanItemToTransaction(profileId, id), onSuccess: inv });
    const update = useMutation({ mutationFn: ({ id, payload }) => updateMonthlyPlanItem(profileId, id, payload), onSuccess: inv });
    const cancel = useMutation({ mutationFn: (id) => updateMonthlyPlanItem(profileId, id, { status: 'CANCELLED' }), onSuccess: inv });
    const markPaid = useMutation({ mutationFn: (id) => updateMonthlyPlanItem(profileId, id, { status: 'PAID' }), onSuccess: inv });
    const markCollected = useMutation({ mutationFn: (id) => updateMonthlyPlanItem(profileId, id, { status: 'COLLECTED' }), onSuccess: inv });
    const lastActionError = conv.error ?? update.error ?? cancel.error ?? markPaid.error ?? markCollected.error ?? del.error;
    const actionErrorMessage = lastActionError ? getApiErrorMessage(lastActionError) : null;
    const quickPreviewMutation = useMutation({ mutationFn: () => previewMonthlyPlanQuickCapture(profileId, { rawText: quickText, defaultYear: year, defaultMonth: month, defaultCurrency: 'ARS' }), onSuccess: (r) => { setQuickError(''); setQuickPreview(r); setQuickForm(r.parsed); }, onError: (e) => { setQuickPreview(null); setQuickForm(null); setQuickError(getApiErrorMessage(e)); } });
    const quickCommitMutation = useMutation({ mutationFn: () => commitMonthlyPlanQuickCapture(profileId, { rawText: quickText, payload: quickForm }), onSuccess: () => { setQuickText(''); setQuickPreview(null); setQuickForm(null); inv(); } });
    return _jsx(AppLayout, { children: _jsxs("div", { className: 'page-stack', children: [_jsxs("section", { className: 'card page-header', children: [_jsx("h1", { children: "Planificaci\u00F3n mensual" }), _jsx("p", { className: 'secondary-text', children: "Carg\u00E1 ingresos, gastos y pendientes del mes. Despu\u00E9s convert\u00ED lo confirmado en movimientos reales." }), _jsx(MonthSelector, { year: year, month: month, onYearChange: setYear, onMonthChange: setMonth }), _jsx("div", { className: 'page-actions', children: _jsx(Link, { to: `/profiles/${profileId}/dashboard`, children: "Ver dashboard" }) })] }), _jsx(MonthlyPlanningGuide, { summary: q.data }), _jsx(QuickCapturePanel, { input: quickText, onChange: setQuickText, onAnalyze: () => quickPreviewMutation.mutate(), canAnalyze: Boolean(quickText.trim()), error: quickError, showDiscard: Boolean(quickPreview), onDiscard: () => { setQuickPreview(null); setQuickForm(null); }, onClear: () => { setQuickText(''); setQuickError(''); }, isAnalyzing: quickPreviewMutation.isPending, children: quickPreview && quickForm && _jsx(QuickCapturePreviewForm, { profileId: profileId, preview: quickPreview, form: quickForm, setForm: setQuickForm, accounts: aq.data ?? [], categories: cq.data ?? [], onConfirm: () => quickCommitMutation.mutate() }) }), _jsx(PlanningSummaryCards, { summary: q.data }), _jsx(MonthlyPlanningChecklist, { summary: q.data, items: q.data?.items ?? [], onApply: setTableFilter }), _jsx(MonthlyPlanItemsTable, { profileId: profileId, items: q.data?.items ?? [], accounts: aq.data ?? [], categories: cq.data ?? [], onConvert: (id) => conv.mutate(id), onCancel: (id) => cancel.mutate(id), onDelete: (id) => del.mutate(id), onUpdate: (id, payload) => update.mutateAsync({ id, payload }).then(() => undefined), onMarkPaid: (id) => markPaid.mutate(id), onMarkCollected: (id) => markCollected.mutate(id), pendingActionId: conv.variables ?? update.variables?.id ?? cancel.variables ?? markPaid.variables ?? markCollected.variables ?? del.variables ?? null, actionError: actionErrorMessage, externalFilterKey: tableFilter }), _jsx(StructuredPlanItemForm, { form: form, setForm: setForm, accounts: aq.data ?? [], categories: cq.data ?? [], onCreate: () => create.mutate() })] }) });
}
