import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { listAccounts } from '../../api/accountsApi';
import { listCategories } from '../../api/categoriesApi';
import { getApiErrorMessage } from '../../api/http';
import { commitMonthlyPlanQuickCapture, previewMonthlyPlanQuickCapture } from '../../api/monthlyPlanQuickCaptureApi';
import { convertMonthlyPlanItemToTransaction, createMonthlyPlanItem, deleteMonthlyPlanItem, getMonthlyPlan, updateMonthlyPlanItem } from '../../api/monthlyPlanningApi';
import { AppLayout } from '../../components/layout/AppLayout';
import { MonthSelector } from '../../components/ui/MonthSelector';
import { PlanningSummaryCards } from './components/PlanningSummaryCards';
import { MonthlyPlanItemsTable } from './components/MonthlyPlanItemsTable';
import { QuickCapturePanel } from './components/QuickCapturePanel';
import { QuickCapturePreviewForm } from './components/QuickCapturePreviewForm';
import { StructuredPlanItemForm } from './components/StructuredPlanItemForm';
import type { MonthlyPlanItemCreatePayload, MonthlyPlanItemUpdatePayload, MonthlyPlanSummary, QuickCapturePreviewResponse } from '../../domain/types';

export function MonthlyPlanningPage() { const { profileId = '' } = useParams(); const qc = useQueryClient(); const d = new Date(); const [year, setYear] = useState(d.getFullYear()); const [month, setMonth] = useState(d.getMonth() + 1);
const [quickText, setQuickText] = useState(''); const [quickPreview, setQuickPreview] = useState<QuickCapturePreviewResponse | null>(null); const [quickForm, setQuickForm] = useState<MonthlyPlanItemCreatePayload | null>(null); const [quickError, setQuickError] = useState('');
const [form, setForm] = useState<MonthlyPlanItemCreatePayload>({ type: 'EXPENSE', title: '', periodYear: year, periodMonth: month, priority: 'IMPORTANT', status: 'ESTIMATED', currency: 'ARS' });
const inv = () => { qc.invalidateQueries({ queryKey: ['planning', profileId, year, month] }); qc.invalidateQueries({ queryKey: ['dashboard', profileId, year, month] }); qc.invalidateQueries({ queryKey: ['tx', profileId, year, month] }); };
const q = useQuery<MonthlyPlanSummary>({ queryKey: ['planning', profileId, year, month], queryFn: () => getMonthlyPlan(profileId, year, month), enabled: Boolean(profileId) });
const aq = useQuery({ queryKey: ['accounts', profileId], queryFn: () => listAccounts(profileId), enabled: Boolean(profileId) }); const cq = useQuery({ queryKey: ['categories', profileId], queryFn: () => listCategories(profileId, true), enabled: Boolean(profileId) });
const create = useMutation({ mutationFn: () => createMonthlyPlanItem(profileId, { ...form, periodYear: year, periodMonth: month }), onSuccess: () => { setForm({ ...form, title: '' }); inv(); } });
const del = useMutation({ mutationFn: (id: string) => deleteMonthlyPlanItem(profileId, id), onSuccess: inv });
const conv = useMutation({ mutationFn: (id: string) => convertMonthlyPlanItemToTransaction(profileId, id), onSuccess: inv });
const update = useMutation({ mutationFn: ({ id, payload }: { id: string; payload: MonthlyPlanItemUpdatePayload }) => updateMonthlyPlanItem(profileId, id, payload), onSuccess: inv });
const cancel = useMutation({ mutationFn: (id: string) => updateMonthlyPlanItem(profileId, id, { status: 'CANCELLED' }), onSuccess: inv });
const markPaid = useMutation({ mutationFn: (id: string) => updateMonthlyPlanItem(profileId, id, { status: 'PAID' }), onSuccess: inv });
const markCollected = useMutation({ mutationFn: (id: string) => updateMonthlyPlanItem(profileId, id, { status: 'COLLECTED' }), onSuccess: inv });
const lastActionError = conv.error ?? update.error ?? cancel.error ?? markPaid.error ?? markCollected.error ?? del.error;
const actionErrorMessage = lastActionError ? getApiErrorMessage(lastActionError) : null;
const quickPreviewMutation = useMutation({ mutationFn: () => previewMonthlyPlanQuickCapture(profileId, { rawText: quickText, defaultYear: year, defaultMonth: month, defaultCurrency: 'ARS' }), onSuccess: (r) => { setQuickError(''); setQuickPreview(r); setQuickForm(r.parsed); }, onError: (e) => { setQuickPreview(null); setQuickForm(null); setQuickError(getApiErrorMessage(e)); } });
const quickCommitMutation = useMutation({ mutationFn: () => commitMonthlyPlanQuickCapture(profileId, { rawText: quickText, payload: quickForm as MonthlyPlanItemCreatePayload }), onSuccess: () => { setQuickText(''); setQuickPreview(null); setQuickForm(null); inv(); } });
return <AppLayout><div className='page-stack'><section className='card page-header'><h1>Planificación mensual</h1><MonthSelector year={year} month={month} onYearChange={setYear} onMonthChange={setMonth} /><div className='page-actions'><Link to={`/profiles/${profileId}/dashboard`}>Ver dashboard</Link></div></section><QuickCapturePanel input={quickText} onChange={setQuickText} onAnalyze={() => quickPreviewMutation.mutate()} canAnalyze={Boolean(quickText.trim())} error={quickError} showDiscard={Boolean(quickPreview)} onDiscard={() => { setQuickPreview(null); setQuickForm(null); }}>{quickPreview && quickForm && <QuickCapturePreviewForm preview={quickPreview} form={quickForm} setForm={setQuickForm} accounts={aq.data ?? []} categories={cq.data ?? []} onConfirm={() => quickCommitMutation.mutate()} />}</QuickCapturePanel><PlanningSummaryCards summary={q.data} /><MonthlyPlanItemsTable items={q.data?.items ?? []} accounts={aq.data ?? []} categories={cq.data ?? []} onConvert={(id) => conv.mutate(id)} onCancel={(id) => cancel.mutate(id)} onDelete={(id) => del.mutate(id)} onUpdate={(id, payload) => update.mutateAsync({ id, payload }).then(() => undefined)} onMarkPaid={(id) => markPaid.mutate(id)} onMarkCollected={(id) => markCollected.mutate(id)} pendingActionId={conv.variables ?? update.variables?.id ?? cancel.variables ?? markPaid.variables ?? markCollected.variables ?? del.variables ?? null} actionError={actionErrorMessage} /><StructuredPlanItemForm form={form} setForm={setForm} accounts={aq.data ?? []} categories={cq.data ?? []} onCreate={() => create.mutate()} /></div></AppLayout>; }
