package com.hogaria.entity;

public enum ImportRowStatus {
    READY,
    NEEDS_CATEGORY,
    REVIEW,
    DUPLICATE,
    DUPLICATE_EXACT,
    POSSIBLE_INTERNAL_TRANSFER,
    INTERNAL_TRANSFER_MATCHED,
    POSSIBLE_CROSS_SOURCE_DUPLICATE,
    IMPORTED,
    SKIPPED,
    ERROR
}
