package com.hogaria.service;

import com.hogaria.dto.BudgetDtos.*;
import com.hogaria.entity.*;
import com.hogaria.exception.*;
import com.hogaria.repository.*;
import java.math.*;
import java.time.*;
import java.util.*;
import java.util.function.Function;
import java.util.stream.Collectors;
import org.springframework.stereotype.Service;

@Service
public class BudgetService {
private final FinancialProfileRepository pr; private final BudgetYearRepository byr; private final BudgetMonthRepository bmr; private final BudgetCategoryItemRepository bir; private final CategoryRepository cr; private final MoneyTransactionRepository tr;
public BudgetService(FinancialProfileRepository pr,BudgetYearRepository byr,BudgetMonthRepository bmr,BudgetCategoryItemRepository bir,CategoryRepository cr,MoneyTransactionRepository tr){this.pr=pr;this.byr=byr;this.bmr=bmr;this.bir=bir;this.cr=cr;this.tr=tr;}
private void own(UUID profileId,UUID userId){pr.findByIdAndUserId(profileId,userId).orElseThrow(()->new ForbiddenException("Profile does not belong to user"));}
private boolean budgetable(Category.Type type){return type==Category.Type.FIXED_EXPENSE||type==Category.Type.VARIABLE_EXPENSE||type==Category.Type.SAVING||type==Category.Type.DEBT||type==Category.Type.INVESTMENT;}
public BudgetYearResponse createBudgetYear(UUID userId,UUID profileId,BudgetYearCreateRequest r){own(profileId,userId); if(byr.existsByProfileIdAndYear(profileId,r.year())) throw new BadRequestException("Budget year already exists"); return y(byr.save(BudgetYear.builder().profileId(profileId).year(r.year()).targetIncome(r.targetIncome()).targetSaving(r.targetSaving()).notes(r.notes()).build()));}
public List<BudgetYearResponse> listBudgetYears(UUID userId,UUID profileId){own(profileId,userId); return byr.findByProfileId(profileId).stream().map(this::y).toList();}
public BudgetYearResponse getBudgetYear(UUID userId,UUID profileId,Integer year){own(profileId,userId); return y(byr.findByProfileIdAndYear(profileId,year).orElseThrow(()->new NotFoundException("Budget year not found")));}
public BudgetYearResponse updateBudgetYear(UUID userId,UUID profileId,Integer year,BudgetYearUpdateRequest r){own(profileId,userId); var by=byr.findByProfileIdAndYear(profileId,year).orElseThrow(()->new NotFoundException("Budget year not found")); by.setTargetIncome(r.targetIncome());by.setTargetSaving(r.targetSaving());by.setNotes(r.notes()); return y(byr.save(by));}
public BudgetMonthResponse createBudgetMonth(UUID userId,UUID profileId,Integer year,BudgetMonthCreateRequest r){own(profileId,userId); var by=byr.findByProfileIdAndYear(profileId,year).orElseGet(()->byr.save(BudgetYear.builder().profileId(profileId).year(year).build())); var bm=bmr.findByBudgetYearIdAndMonth(by.getId(),r.month()).orElseGet(()->bmr.save(BudgetMonth.builder().budgetYearId(by.getId()).month(r.month()).notes(r.notes()).build())); return m(bm);}
public BudgetMonthResponse getBudgetMonth(UUID userId,UUID profileId,Integer year,Integer month){own(profileId,userId); var by=byr.findByProfileIdAndYear(profileId,year).orElseThrow(()->new NotFoundException("Budget year not found")); return m(bmr.findByBudgetYearIdAndMonth(by.getId(),month).orElseThrow(()->new NotFoundException("Budget month not found")));}
public BudgetMonthResponse updateBudgetMonth(UUID userId,UUID id,BudgetMonthUpdateRequest r){var bm=bmr.findById(id).orElseThrow(()->new NotFoundException("Budget month not found")); var by=byr.findById(bm.getBudgetYearId()).orElseThrow(); own(by.getProfileId(),userId); bm.setNotes(r.notes()); return m(bmr.save(bm));}
public BudgetCategoryItemResponse upsertBudgetCategoryItem(UUID userId,UUID budgetMonthId,BudgetCategoryItemUpsertRequest r){var bm=bmr.findById(budgetMonthId).orElseThrow(()->new NotFoundException("Budget month not found")); var by=byr.findById(bm.getBudgetYearId()).orElseThrow(); own(by.getProfileId(),userId); var c=cr.findById(r.categoryId()).orElseThrow(()->new NotFoundException("Category not found")); if(c.getProfileId()!=null && !c.getProfileId().equals(by.getProfileId())) throw new ForbiddenException("Category does not belong to profile"); var i=bir.findByBudgetMonthIdAndCategoryId(budgetMonthId,r.categoryId()).orElseGet(()->BudgetCategoryItem.builder().budgetMonthId(budgetMonthId).categoryId(r.categoryId()).build()); i.setBudgetAmount(r.budgetAmount()); return item(bir.save(i),c);}
public void deleteBudgetCategoryItem(UUID userId,UUID itemId){var i=bir.findById(itemId).orElseThrow(()->new NotFoundException("Budget item not found")); var bm=bmr.findById(i.getBudgetMonthId()).orElseThrow(); var by=byr.findById(bm.getBudgetYearId()).orElseThrow(); own(by.getProfileId(),userId); bir.delete(i);} 
public BudgetComparisonResponse getComparison(UUID userId,UUID profileId,Integer year,Integer month){own(profileId,userId); var bm=getBudgetMonthEntity(profileId,year,month); var items=bir.findByBudgetMonthId(bm.getId()); var from=LocalDate.of(year,month,1); var to=from.withDayOfMonth(from.lengthOfMonth()); var txs=tr.findByProfileIdAndBudgetDateBetween(profileId,from,to).stream().filter(t->t.getStatus()==MoneyTransaction.Status.CONFIRMED).toList();
var catIds=new HashSet<UUID>(); items.forEach(i->catIds.add(i.getCategoryId())); txs.forEach(t->catIds.add(t.getCategoryId())); var cmap=cr.findAllById(catIds).stream().collect(Collectors.toMap(Category::getId,Function.identity()));
var real=txs.stream().filter(t->{var c=cmap.get(t.getCategoryId()); return c!=null && budgetable(c.getType());}).collect(Collectors.groupingBy(MoneyTransaction::getCategoryId,Collectors.reducing(BigDecimal.ZERO,MoneyTransaction::getAmount,BigDecimal::add)));
var imap=items.stream().filter(i->{var c=cmap.get(i.getCategoryId()); return c!=null && budgetable(c.getType());}).collect(Collectors.toMap(BudgetCategoryItem::getCategoryId,Function.identity()));
var comparisonIds=new HashSet<UUID>(); comparisonIds.addAll(real.keySet()); comparisonIds.addAll(imap.keySet());
List<BudgetComparisonItemResponse> out=new ArrayList<>(); for(var cid:comparisonIds){var budget=imap.containsKey(cid)?imap.get(cid).getBudgetAmount():BigDecimal.ZERO; var rv=real.getOrDefault(cid,BigDecimal.ZERO); var diff=budget.subtract(rv); var pct=budget.signum()==0?(rv.signum()==0?BigDecimal.ZERO:new BigDecimal("100")):rv.multiply(new BigDecimal("100")).divide(budget,2,RoundingMode.HALF_UP); var st=pct.compareTo(new BigDecimal("100"))>0|| (budget.signum()==0&&rv.signum()>0)?BudgetStatus.EXCEEDED:(pct.compareTo(new BigDecimal("80"))>0?BudgetStatus.WARNING:BudgetStatus.OK); var c=cmap.get(cid); out.add(new BudgetComparisonItemResponse(cid,c==null?"Unknown":c.getName(),c==null?null:c.getType(),budget,rv,diff,pct,st));}
out.sort(Comparator.comparing(BudgetComparisonItemResponse::categoryName));
var tb=out.stream().map(BudgetComparisonItemResponse::budgetAmount).reduce(BigDecimal.ZERO,BigDecimal::add); var trr=out.stream().map(BudgetComparisonItemResponse::realAmount).reduce(BigDecimal.ZERO,BigDecimal::add); return new BudgetComparisonResponse(profileId,year,month,tb,trr,tb.subtract(trr),out);}
private BudgetMonth getBudgetMonthEntity(UUID profileId,Integer year,Integer month){var by=byr.findByProfileIdAndYear(profileId,year).orElseThrow(()->new NotFoundException("Budget year not found")); return bmr.findByBudgetYearIdAndMonth(by.getId(),month).orElseThrow(()->new NotFoundException("Budget month not found"));}
private BudgetYearResponse y(BudgetYear b){return new BudgetYearResponse(b.getId(),b.getProfileId(),b.getYear(),b.getTargetIncome(),b.getTargetSaving(),b.getNotes(),b.getCreatedAt(),b.getUpdatedAt());}
private BudgetCategoryItemResponse item(BudgetCategoryItem i,Category c){return new BudgetCategoryItemResponse(i.getId(),i.getBudgetMonthId(),i.getCategoryId(),c.getName(),c.getType(),i.getBudgetAmount(),i.getCreatedAt(),i.getUpdatedAt());}
private BudgetMonthResponse m(BudgetMonth b){var cats=cr.findAllById(bir.findByBudgetMonthId(b.getId()).stream().map(BudgetCategoryItem::getCategoryId).toList()).stream().collect(Collectors.toMap(Category::getId,Function.identity())); var items=bir.findByBudgetMonthId(b.getId()).stream().map(i->item(i,cats.get(i.getCategoryId()))).toList(); return new BudgetMonthResponse(b.getId(),b.getBudgetYearId(),b.getMonth(),b.getNotes(),items,b.getCreatedAt(),b.getUpdatedAt());}
}
