package com.hogaria.service;

public enum CashFlowTreatment {
  CONSUMPTION_EXPENSE,
  FIXED_CONSUMPTION_EXPENSE,
  VARIABLE_CONSUMPTION_EXPENSE,
  DEBT_OUTFLOW,
  DEBT_INTEREST,
  SAVING_OUTFLOW,
  INVESTMENT_OUTFLOW,
  RECOVERABLE_OUTFLOW,
  PRINCIPAL_RECOVERY,
  REFUND_OR_REIMBURSEMENT,
  EARNED_INCOME,
  INTEREST_INCOME,
  INTERNAL_TRANSFER,
  EXTERNAL_TRANSFER,
  CASH_WITHDRAWAL,
  LOAN_ORIGINATION,
  NEUTRAL_ADJUSTMENT,
  UNKNOWN
}
