package com.hogaria.service;
import com.hogaria.dto.CategoryDtos.*;import com.hogaria.entity.Category;import com.hogaria.exception.*;import com.hogaria.repository.*;import java.util.*;import org.springframework.stereotype.Service;
@Service
public class CategoryService {
  private final CategoryRepository categoryRepository; private final FinancialProfileRepository profileRepository;
  private final CategoryKeyNormalizer categoryKeyNormalizer;
  public CategoryService(CategoryRepository categoryRepository, FinancialProfileRepository profileRepository, CategoryKeyNormalizer categoryKeyNormalizer){this.categoryRepository=categoryRepository;this.profileRepository=profileRepository;this.categoryKeyNormalizer=categoryKeyNormalizer;}
  public CategoryResponse create(UUID userId, UUID profileId, CategoryCreateRequest r){ensureProfile(userId,profileId); if(r.scope()==Category.Scope.GLOBAL) throw new BadRequestException("GLOBAL scope not allowed"); validateParent(r.parentId(), profileId); var key=categoryKeyNormalizer.normalize(r.name()); rejectDuplicateKey(profileId,key,r.type(),null); var c=Category.builder().profileId(profileId).parentId(r.parentId()).name(r.name()).categoryKey(key).type(r.type()).scope(r.scope()).active(true).build(); return toResponse(categoryRepository.save(c));}
  public List<CategoryResponse> list(UUID userId, UUID profileId, boolean includeGlobal){ensureProfile(userId,profileId); var list=new ArrayList<>(categoryRepository.findByProfileIdAndActiveTrue(profileId)); if(includeGlobal) list.addAll(categoryRepository.findByProfileIdIsNullAndActiveTrue()); return list.stream().map(this::toResponse).toList();}
  public CategoryResponse get(UUID userId, UUID id){var c=categoryRepository.findById(id).orElseThrow(()->new NotFoundException("Category not found")); if(c.getProfileId()!=null) ensureProfile(userId,c.getProfileId()); return toResponse(c);} 
  public CategoryResponse update(UUID userId, UUID id, CategoryUpdateRequest r){var c=categoryRepository.findById(id).orElseThrow(()->new NotFoundException("Category not found")); if(c.getProfileId()==null) throw new ForbiddenException("Global categories cannot be edited"); ensureProfile(userId,c.getProfileId()); if(r.parentId()!=null) validateParent(r.parentId(), c.getProfileId()); var nextName=r.name()!=null?r.name():c.getName(); var nextType=r.type()!=null?r.type():c.getType(); var nextKey=categoryKeyNormalizer.normalize(nextName); if(!Boolean.FALSE.equals(r.active())) rejectDuplicateKey(c.getProfileId(),nextKey,nextType,c.getId()); if(r.name()!=null){c.setName(r.name());c.setCategoryKey(nextKey);} if(r.type()!=null)c.setType(r.type()); if(r.scope()!=null && r.scope()!=Category.Scope.GLOBAL)c.setScope(r.scope()); if(r.parentId()!=null)c.setParentId(r.parentId()); if(r.active()!=null)c.setActive(r.active()); return toResponse(categoryRepository.save(c));}
  public void deactivate(UUID userId, UUID id){var c=categoryRepository.findById(id).orElseThrow(()->new NotFoundException("Category not found")); if(c.getProfileId()==null) throw new ForbiddenException("Global categories cannot be deactivated"); ensureProfile(userId,c.getProfileId()); c.setActive(false); categoryRepository.save(c);}  
  private void validateParent(UUID parentId, UUID profileId){ if(parentId==null) return; var p=categoryRepository.findById(parentId).orElseThrow(()->new BadRequestException("Parent category not found")); if(p.getProfileId()!=null && !Objects.equals(p.getProfileId(), profileId)) throw new BadRequestException("Parent category must belong to same profile or be global"); }
  private void rejectDuplicateKey(UUID profileId,String key,Category.Type type,UUID excludeId){ if(key!=null && categoryRepository.existsActiveProfileDuplicateKey(profileId,key,type,excludeId)) throw new DomainConflictException("Ya existe una categoría activa equivalente para ese perfil y tipo.","CATEGORY_DUPLICATE_NORMALIZED",List.of(new ErrorResponse.Detail("categoryKey",key),new ErrorResponse.Detail("type",type.name()))); }
  private void ensureProfile(UUID userId, UUID profileId){profileRepository.findByIdAndUserId(profileId,userId).orElseThrow(()->new ForbiddenException("Profile does not belong to user"));}
  private CategoryResponse toResponse(Category c){return new CategoryResponse(c.getId(),c.getProfileId(),c.getParentId(),c.getName(),c.getCategoryKey(),c.getType(),c.getScope(),c.getDefaultMovementType(),c.getBudgetable(),c.getTechnical(),c.getActive(),c.getCreatedAt(),c.getUpdatedAt());}
}
