package com.hogaria.service;

import com.hogaria.dto.DashboardDtos.*;import com.hogaria.entity.*;import com.hogaria.exception.ForbiddenException;import com.hogaria.repository.*;import java.math.*;import java.time.*;import java.util.*;import java.util.stream.*;import org.springframework.stereotype.Service;
@Service
public class DashboardService {
  private final FinancialProfileRepository profileRepository; private final MoneyTransactionRepository transactionRepository; private final CategoryRepository categoryRepository; private final BudgetYearRepository budgetYearRepository; private final BudgetMonthRepository budgetMonthRepository; private final BudgetCategoryItemRepository budgetCategoryItemRepository; private final MonthlyPlanItemRepository monthlyPlanItemRepository;
  public DashboardService(FinancialProfileRepository profileRepository, MoneyTransactionRepository transactionRepository, CategoryRepository categoryRepository, BudgetYearRepository budgetYearRepository, BudgetMonthRepository budgetMonthRepository, BudgetCategoryItemRepository budgetCategoryItemRepository, MonthlyPlanItemRepository monthlyPlanItemRepository){this.profileRepository=profileRepository;this.transactionRepository=transactionRepository;this.categoryRepository=categoryRepository;this.budgetYearRepository=budgetYearRepository;this.budgetMonthRepository=budgetMonthRepository;this.budgetCategoryItemRepository=budgetCategoryItemRepository;this.monthlyPlanItemRepository=monthlyPlanItemRepository;}
  public DashboardSummaryResponse getMonthlySummary(UUID userId, UUID profileId, int year, int month){profileRepository.findByIdAndUserId(profileId,userId).orElseThrow(()->new ForbiddenException("Profile does not belong to user")); var from=LocalDate.of(year,month,1); var to=from.withDayOfMonth(from.lengthOfMonth()); var txs=transactionRepository.findByProfileIdAndBudgetDateBetween(profileId,from,to).stream().filter(t->t.getStatus()==MoneyTransaction.Status.CONFIRMED).toList(); var categories=categoryRepository.findAllById(txs.stream().map(MoneyTransaction::getCategoryId).collect(Collectors.toSet())).stream().collect(Collectors.toMap(Category::getId,c->c));
    BigDecimal income=sum(txs.stream().filter(t->t.getMovementType()==MoneyTransaction.MovementType.INCOME).map(MoneyTransaction::getAmount).toList());
    BigDecimal fixed=sumByType(txs,categories,Category.Type.FIXED_EXPENSE); BigDecimal variable=sumByType(txs,categories,Category.Type.VARIABLE_EXPENSE);
    BigDecimal savings=sum(txs.stream().filter(t->t.getMovementType()==MoneyTransaction.MovementType.SAVING || categories.get(t.getCategoryId())!=null && categories.get(t.getCategoryId()).getType()==Category.Type.SAVING).map(MoneyTransaction::getAmount).toList());
    BigDecimal totalExpenses=fixed.add(variable); BigDecimal balance=income.subtract(totalExpenses).subtract(savings);
    BigDecimal fp=percent(fixed,income), vp=percent(variable,income), sp=percent(savings,income);
    String health=balance.signum()<0?"CRITICAL":(sp.compareTo(new BigDecimal("20"))>=0&&fp.compareTo(new BigDecimal("50"))<=0&&vp.compareTo(new BigDecimal("30"))<=0?"EXCELLENT":(savings.signum()>0?"HEALTHY":"WARNING"));
    var breakdown=txs.stream().collect(Collectors.groupingBy(MoneyTransaction::getCategoryId)).entrySet().stream().map(e->{var c=categories.get(e.getKey()); var total=sum(e.getValue().stream().map(MoneyTransaction::getAmount).toList()); return new CategorySummaryResponse(e.getKey(),c==null?"Unknown":c.getName(),c==null?null:c.getType(),total,percent(total,income),e.getValue().size());}).toList();
    BudgetSummaryResponse bs=null; var by=budgetYearRepository.findByProfileIdAndYear(profileId,year); if(by.isPresent()){ var bm=budgetMonthRepository.findByBudgetYearIdAndMonth(by.get().getId(),month); if(bm.isPresent()){ var itemMap=budgetCategoryItemRepository.findByBudgetMonthId(bm.get().getId()).stream().collect(Collectors.toMap(BudgetCategoryItem::getCategoryId,BudgetCategoryItem::getBudgetAmount)); BigDecimal tb=itemMap.values().stream().reduce(BigDecimal.ZERO,BigDecimal::add); BigDecimal tr=txs.stream().filter(t->itemMap.containsKey(t.getCategoryId())).map(MoneyTransaction::getAmount).reduce(BigDecimal.ZERO,BigDecimal::add); long ex=itemMap.entrySet().stream().filter(e->{var rv=txs.stream().filter(t->t.getCategoryId().equals(e.getKey())).map(MoneyTransaction::getAmount).reduce(BigDecimal.ZERO,BigDecimal::add); return e.getValue().signum()==0?rv.signum()>0:rv.multiply(new BigDecimal("100")).divide(e.getValue(),2,RoundingMode.HALF_UP).compareTo(new BigDecimal("100"))>0;}).count(); long wr=itemMap.entrySet().stream().filter(e->{if(e.getValue().signum()==0)return false; var rv=txs.stream().filter(t->t.getCategoryId().equals(e.getKey())).map(MoneyTransaction::getAmount).reduce(BigDecimal.ZERO,BigDecimal::add); var p=rv.multiply(new BigDecimal("100")).divide(e.getValue(),2,RoundingMode.HALF_UP); return p.compareTo(new BigDecimal("80"))>0 && p.compareTo(new BigDecimal("100"))<=0;}).count(); bs=new BudgetSummaryResponse(tb,tr,tb.subtract(tr),ex,wr); }}
    var planning=buildPlanning(profileId, year, month); var op=buildOperational(income,totalExpenses,savings,balance,planning,txs.isEmpty());
    return new DashboardSummaryResponse(new MonthlyBalanceResponse(income,totalExpenses,savings,balance),new FiftyThirtyTwentyResponse(fp,vp,sp),fixed,variable,health,breakdown,bs,planning,op);
  }
  private PlanningDashboardSummaryResponse buildPlanning(UUID profileId,int year,int month){ var items=monthlyPlanItemRepository.findByProfileIdAndPeriodYearAndPeriodMonth(profileId,year,month); BigDecimal inMin=BigDecimal.ZERO,inMax=BigDecimal.ZERO,exMin=BigDecimal.ZERO,exMax=BigDecimal.ZERO,recMin=BigDecimal.ZERO,recMax=BigDecimal.ZERO,nMin=BigDecimal.ZERO,nMax=BigDecimal.ZERO,pIn=BigDecimal.ZERO,pEx=BigDecimal.ZERO; int unpriced=0,due7=0,cancelled=0,converted=0; var pend=Set.of(MonthlyPlanItem.Status.DRAFT,MonthlyPlanItem.Status.ESTIMATED,MonthlyPlanItem.Status.SCHEDULED,MonthlyPlanItem.Status.DUE); var today=LocalDate.now();
    for(var i:items){ var c=calc(i); boolean isCancelled=i.getStatus()==MonthlyPlanItem.Status.CANCELLED; if(isCancelled) cancelled++; if(i.getTransactionId()!=null) converted++; if(!isCancelled&&i.getAmount()==null&&i.getMinAmount()==null&&i.getMaxAmount()==null) unpriced++; if(!isCancelled&&i.getExpectedDate()!=null&&!i.getExpectedDate().isBefore(today)&&!i.getExpectedDate().isAfter(today.plusDays(7))) due7++; if(isCancelled||i.getType()==MonthlyPlanItem.Type.TODO) continue; boolean inc=i.getType()==MonthlyPlanItem.Type.INCOME||i.getType()==MonthlyPlanItem.Type.RECOVERY; if(inc){inMin=inMin.add(c.grossMin); inMax=inMax.add(c.grossMax); nMin=nMin.add(c.netMin); nMax=nMax.add(c.netMax); if(pend.contains(i.getStatus())) pIn=pIn.add(c.netMax);} else {exMin=exMin.add(c.grossMin); exMax=exMax.add(c.grossMax); recMin=recMin.add(c.recoveryMin); recMax=recMax.add(c.recoveryMax); nMin=nMin.subtract(c.netMax); nMax=nMax.subtract(c.netMin); if(pend.contains(i.getStatus())) pEx=pEx.add(c.netMax);} }
    return new PlanningDashboardSummaryResponse(inMin,inMax,exMin,exMax,recMin,recMax,nMin,nMax,pIn,pEx,unpriced,due7,items.size(),cancelled,converted);
  }
  private DashboardOperationalSummaryResponse buildOperational(BigDecimal income,BigDecimal totalExpenses,BigDecimal savings,BigDecimal balance,PlanningDashboardSummaryResponse p,boolean noConfirmed){ BigDecimal deltaMin=p.projectedNetMin().subtract(balance); BigDecimal deltaMax=p.projectedNetMax().subtract(balance); var risk="OK"; var alerts=new ArrayList<String>(); if(p.projectedNetMin().signum()<0){risk="CRITICAL"; alerts.add("El neto proyectado mínimo queda negativo.");} else if(p.projectedNetMax().compareTo(balance)<0 || p.pendingExpense().compareTo(p.pendingIncome().add(balance))>0){risk="RISK";} else if(p.unpricedCount()>0||p.dueNext7DaysCount()>0){risk="WATCH";}
    if(p.unpricedCount()>0) alerts.add("Hay "+p.unpricedCount()+" ítems sin cotizar."); if(p.dueNext7DaysCount()>0) alerts.add("Hay "+p.dueNext7DaysCount()+" vencimientos/cobros en los próximos 7 días."); if(p.pendingExpense().compareTo(p.pendingIncome().add(balance))>0) alerts.add("Los egresos pendientes superan los ingresos pendientes más el saldo confirmado."); if(p.plannedItemsCount()>0&&noConfirmed) alerts.add("Hay planificación cargada pero todavía no hay movimientos confirmados.");
    return new DashboardOperationalSummaryResponse(income,totalExpenses,savings,balance,p.projectedNetMin(),p.projectedNetMax(),deltaMin,deltaMax,p.pendingIncome(),p.pendingExpense(),p.totalRecoveryMin(),p.totalRecoveryMax(),p.unpricedCount(),p.dueNext7DaysCount(),risk,alerts);
  }
  record C(BigDecimal grossMin,BigDecimal grossMax,BigDecimal recoveryMin,BigDecimal recoveryMax,BigDecimal netMin,BigDecimal netMax){}
  private C calc(MonthlyPlanItem i){ var gMin=i.getAmount()!=null?i.getAmount():i.getMinAmount()!=null?i.getMinAmount():BigDecimal.ZERO; var gMax=i.getAmount()!=null?i.getAmount():i.getMaxAmount()!=null?i.getMaxAmount():i.getMinAmount()!=null?i.getMinAmount():BigDecimal.ZERO; var rFix=i.getExpectedRecoveryAmount(); var pr=i.getExpectedRecoveryPercent()==null?BigDecimal.ZERO:i.getExpectedRecoveryPercent().divide(new BigDecimal("100"),6,RoundingMode.HALF_UP); var rMin=rFix!=null?rFix:gMin.multiply(pr); var rMax=rFix!=null?rFix:gMax.multiply(pr); return new C(gMin,gMax,rMin,rMax,gMin.subtract(rMax),gMax.subtract(rMin)); }
  private BigDecimal sumByType(List<MoneyTransaction> txs, Map<UUID,Category> m, Category.Type type){ return sum(txs.stream().filter(t->m.get(t.getCategoryId())!=null && m.get(t.getCategoryId()).getType()==type).map(MoneyTransaction::getAmount).toList()); }
  private BigDecimal sum(List<BigDecimal> values){return values.stream().reduce(BigDecimal.ZERO,BigDecimal::add);} private BigDecimal percent(BigDecimal a, BigDecimal income){ if(income.signum()==0) return BigDecimal.ZERO; return a.multiply(new BigDecimal("100")).divide(income,2,RoundingMode.HALF_UP);} }
