package com.hogaria.service;
import com.hogaria.dto.PlanningDtos.*;import com.hogaria.entity.*;import com.hogaria.exception.*;import com.hogaria.repository.*;import org.springframework.stereotype.Service;import java.math.*;import java.util.*;
@Service public class FinancialGoalService {
private final FinancialGoalRepository repo; private final FinancialProfileRepository pr; private final MoneyTransactionRepository tr; private final CategoryRepository cr;
public FinancialGoalService(FinancialGoalRepository repo, FinancialProfileRepository pr, MoneyTransactionRepository tr, CategoryRepository cr){this.repo=repo;this.pr=pr;this.tr=tr;this.cr=cr;}
private void own(UUID u,UUID p){pr.findByIdAndUserId(p,u).orElseThrow(()->new ForbiddenException("Profile does not belong to user"));}
public List<FinancialGoalResponse> list(UUID u,UUID p){own(u,p); return repo.findByProfileId(p).stream().map(this::to).toList();}
public FinancialGoalResponse create(UUID u,UUID p, FinancialGoalCreateRequest r){own(u,p); var g=repo.save(FinancialGoal.builder().profileId(p).name(r.name()).goalType(r.goalType()).targetAmount(r.targetAmount()).currentAmount(r.currentAmount()).monthlyTargetAmount(r.monthlyTargetAmount()).targetDate(r.targetDate()).priority(r.priority()).notes(r.notes()).status(r.currentAmount().compareTo(r.targetAmount())>=0?GoalStatus.COMPLETED:GoalStatus.ACTIVE).build()); return to(g);} 
public void delete(UUID u,UUID p,UUID id){own(u,p); var g=repo.findById(id).orElseThrow(()->new NotFoundException("Goal not found")); if(!g.getProfileId().equals(p)) throw new ForbiddenException("Goal not in profile"); repo.delete(g);} 
public FinancialGoalResponse emergencyFund(UUID u,UUID p,int months){own(u,p); var txs=tr.findByProfileId(p); var avg=txs.stream().filter(t->t.getMovementType()==MoneyTransaction.MovementType.EXPENSE||t.getMovementType()==MoneyTransaction.MovementType.SAVING).map(t->t.getAmount()).reduce(BigDecimal.ZERO,BigDecimal::add); var target=avg.multiply(BigDecimal.valueOf(months)); var g=repo.save(FinancialGoal.builder().profileId(p).name("Fondo de emergencia").goalType(GoalType.EMERGENCY_FUND).targetAmount(target.max(new BigDecimal("0.01"))).currentAmount(BigDecimal.ZERO).priority(1).status(GoalStatus.ACTIVE).build()); return to(g);} 
private FinancialGoalResponse to(FinancialGoal g){var progress=g.getTargetAmount().signum()==0?BigDecimal.ZERO:g.getCurrentAmount().multiply(new BigDecimal("100")).divide(g.getTargetAmount(),2,RoundingMode.HALF_UP); return new FinancialGoalResponse(g.getId(),g.getProfileId(),g.getName(),g.getGoalType(),g.getTargetAmount(),g.getCurrentAmount(),progress,g.getStatus());}
}
