package com.hogaria.service;
import com.hogaria.dto.MonthlyPlanDtos.*;import com.hogaria.entity.*;import com.hogaria.exception.*;import com.hogaria.repository.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.*;import java.time.*;import java.util.*;
@Service
@Transactional(readOnly = true)
public class MonthlyPlanService {
private final MonthlyPlanItemRepository repo; private final FinancialProfileRepository profiles; private final CategoryRepository categories; private final AccountRepository accounts; private final MoneyTransactionRepository txRepo; private final MonthlyPlanTransactionMatchRepository matchRepo; private final MonthlyPlanItemValidator validator;
public MonthlyPlanService(MonthlyPlanItemRepository repo, FinancialProfileRepository profiles, CategoryRepository categories, AccountRepository accounts, MoneyTransactionRepository txRepo, MonthlyPlanTransactionMatchRepository matchRepo){this.repo=repo;this.profiles=profiles;this.categories=categories;this.accounts=accounts;this.txRepo=txRepo;this.matchRepo=matchRepo;this.validator=new MonthlyPlanItemValidator(categories,accounts);}
private void ensureProfile(UUID profileId, UUID userId){profiles.findByIdAndUserId(profileId,userId).orElseThrow(()->new ForbiddenException("Profile does not belong to user"));}
private void validate(MonthlyPlanItem i){ validator.validate(i,null,false); var c=calc(i); if(i.getExpectedRecoveryAmount()!=null&&i.getExpectedRecoveryAmount().compareTo(c.grossMax)>0) throw new BadRequestException("Recupero no puede superar bruto"); }
private void validateRefs(UUID profileId, UUID accountId, UUID categoryId){ validator.validateReferences(profileId,accountId,categoryId,true,true); }
private YearMonth resolveCreationPeriod(MonthlyPlanItemCreateRequest r){ return r.expectedDate()==null?YearMonth.of(r.periodYear(),r.periodMonth()):YearMonth.from(r.expectedDate()); }
@Transactional
public MonthlyPlanItemResponse create(UUID userId, UUID profileId, MonthlyPlanItemCreateRequest r){ ensureProfile(profileId,userId); var period=resolveCreationPeriod(r); var i=MonthlyPlanItem.builder().profileId(profileId).categoryId(r.categoryId()).accountId(r.accountId()).type(r.type()).title(r.title()).description(r.description()).expectedDate(r.expectedDate()).periodYear(period.getYear()).periodMonth(period.getMonthValue()).amount(r.amount()).minAmount(r.minAmount()).maxAmount(r.maxAmount()).currency(r.currency()==null?"ARS":r.currency()).expectedRecoveryAmount(r.expectedRecoveryAmount()).expectedRecoveryPercent(r.expectedRecoveryPercent()).counterparty(r.counterparty()).installmentNumber(r.installmentNumber()).installmentTotal(r.installmentTotal()).priority(r.priority()==null?MonthlyPlanItem.Priority.IMPORTANT:r.priority()).status(r.status()==null?MonthlyPlanItem.Status.ESTIMATED:r.status()).source(r.source()==null?MonthlyPlanItem.Source.MANUAL:r.source()).build(); validate(i); validateRefs(profileId,i.getAccountId(),i.getCategoryId()); return toResponse(repo.save(i)); }
public MonthlyPlanSummaryResponse summary(UUID userId, UUID profileId, int year, int month){ ensureProfile(profileId,userId); var items=repo.findByProfileIdAndPeriodYearAndPeriodMonth(profileId,year,month).stream().sorted(Comparator.comparing(MonthlyPlanItem::getExpectedDate, Comparator.nullsLast(Comparator.naturalOrder())).thenComparing(MonthlyPlanItem::getPriority).thenComparing(MonthlyPlanItem::getCreatedAt)).toList(); BigDecimal inMin=BigDecimal.ZERO,inMax=BigDecimal.ZERO,exMin=BigDecimal.ZERO,exMax=BigDecimal.ZERO,recMin=BigDecimal.ZERO,recMax=BigDecimal.ZERO,nMin=BigDecimal.ZERO,nMax=BigDecimal.ZERO,pIn=BigDecimal.ZERO,pEx=BigDecimal.ZERO; int unpriced=0,due7=0; var today=LocalDate.now(); var pend=Set.of(MonthlyPlanItem.Status.DRAFT,MonthlyPlanItem.Status.ESTIMATED,MonthlyPlanItem.Status.SCHEDULED,MonthlyPlanItem.Status.DUE);
for(var i:items){ var c=calc(i); boolean cancelled=i.getStatus()==MonthlyPlanItem.Status.CANCELLED; if(i.getAmount()==null&&i.getMinAmount()==null&&i.getMaxAmount()==null) unpriced++; if(!cancelled&&i.getExpectedDate()!=null&&!i.getExpectedDate().isBefore(today)&&!i.getExpectedDate().isAfter(today.plusDays(7))) due7++; if(cancelled||i.getType()==MonthlyPlanItem.Type.TODO) continue; boolean income=i.getType()==MonthlyPlanItem.Type.INCOME||i.getType()==MonthlyPlanItem.Type.RECOVERY; if(income){inMin=inMin.add(c.grossMin); inMax=inMax.add(c.grossMax); nMin=nMin.add(c.netMin); nMax=nMax.add(c.netMax); if(pend.contains(i.getStatus())) pIn=pIn.add(c.netMax);} else {exMin=exMin.add(c.grossMin); exMax=exMax.add(c.grossMax); recMin=recMin.add(c.recoveryMin); recMax=recMax.add(c.recoveryMax); nMin=nMin.subtract(c.netMax); nMax=nMax.subtract(c.netMin); if(pend.contains(i.getStatus())) pEx=pEx.add(c.netMax);} }
return new MonthlyPlanSummaryResponse(inMin,inMax,exMin,exMax,recMin,recMax,nMin,nMax,pIn,pEx,unpriced,due7,items.stream().map(this::toResponse).toList()); }
record C(BigDecimal grossMin,BigDecimal grossMax,BigDecimal recoveryMin,BigDecimal recoveryMax,BigDecimal netMin,BigDecimal netMax){}
private C calc(MonthlyPlanItem i){ var gMin=i.getAmount()!=null?i.getAmount():i.getMinAmount()!=null?i.getMinAmount():BigDecimal.ZERO; var gMax=i.getAmount()!=null?i.getAmount():i.getMaxAmount()!=null?i.getMaxAmount():i.getMinAmount()!=null?i.getMinAmount():BigDecimal.ZERO; var rFix=i.getExpectedRecoveryAmount(); var p=i.getExpectedRecoveryPercent()==null?BigDecimal.ZERO:i.getExpectedRecoveryPercent().divide(new BigDecimal("100"), 6, RoundingMode.HALF_UP); var rMin=rFix!=null?rFix:gMin.multiply(p); var rMax=rFix!=null?rFix:gMax.multiply(p); return new C(gMin,gMax,rMin,rMax,gMin.subtract(rMax),gMax.subtract(rMin));}
private MonthlyPlanItemResponse toResponse(MonthlyPlanItem i){var c=calc(i);return new MonthlyPlanItemResponse(i.getId(),i.getProfileId(),i.getCategoryId(),i.getAccountId(),i.getType(),i.getTitle(),i.getDescription(),i.getExpectedDate(),i.getPeriodYear(),i.getPeriodMonth(),i.getAmount(),i.getMinAmount(),i.getMaxAmount(),i.getCurrency(),i.getExpectedRecoveryAmount(),i.getExpectedRecoveryPercent(),i.getCounterparty(),i.getInstallmentNumber(),i.getInstallmentTotal(),i.getPriority(),i.getStatus(),i.getSource(),i.getTransactionId(),c.grossMin,c.grossMax,c.recoveryMin,c.recoveryMax,c.netMin,c.netMax,i.getCreatedAt(),i.getUpdatedAt());}
@Transactional
public MonthlyPlanItemResponse update(UUID userId, UUID profileId, UUID itemId, MonthlyPlanItemUpdateRequest r){ ensureProfile(profileId,userId); var i=repo.findByIdAndProfileId(itemId,profileId).orElseThrow(()->new NotFoundException("Item no encontrado")); if(Boolean.TRUE.equals(r.clearExpectedDate())) i.setExpectedDate(null); if(Boolean.TRUE.equals(r.clearAmount())) i.setAmount(null); if(Boolean.TRUE.equals(r.clearRange())){i.setMinAmount(null);i.setMaxAmount(null);} if(Boolean.TRUE.equals(r.clearRecovery())){i.setExpectedRecoveryAmount(null);i.setExpectedRecoveryPercent(null);} if(Boolean.TRUE.equals(r.clearCounterparty())) i.setCounterparty(null); if(Boolean.TRUE.equals(r.clearInstallment())){i.setInstallmentNumber(null);i.setInstallmentTotal(null);} if(Boolean.TRUE.equals(r.clearCategory())) i.setCategoryId(null); if(Boolean.TRUE.equals(r.clearAccount())) i.setAccountId(null);
if(r.type()!=null)i.setType(r.type()); if(r.title()!=null)i.setTitle(r.title()); if(r.description()!=null)i.setDescription(r.description()); if(r.expectedDate()!=null)i.setExpectedDate(r.expectedDate()); if(r.periodYear()!=null)i.setPeriodYear(r.periodYear()); if(r.periodMonth()!=null)i.setPeriodMonth(r.periodMonth()); if(r.amount()!=null)i.setAmount(r.amount()); if(r.minAmount()!=null)i.setMinAmount(r.minAmount()); if(r.maxAmount()!=null)i.setMaxAmount(r.maxAmount()); if(r.currency()!=null)i.setCurrency(r.currency()); if(r.expectedRecoveryAmount()!=null)i.setExpectedRecoveryAmount(r.expectedRecoveryAmount()); if(r.expectedRecoveryPercent()!=null)i.setExpectedRecoveryPercent(r.expectedRecoveryPercent()); if(r.counterparty()!=null)i.setCounterparty(r.counterparty()); if(r.installmentNumber()!=null)i.setInstallmentNumber(r.installmentNumber()); if(r.installmentTotal()!=null)i.setInstallmentTotal(r.installmentTotal()); if(r.priority()!=null)i.setPriority(r.priority()); if(r.status()!=null)i.setStatus(r.status()); if(r.source()!=null)i.setSource(r.source()); if(r.categoryId()!=null)i.setCategoryId(r.categoryId()); if(r.accountId()!=null)i.setAccountId(r.accountId()); validate(i); validateRefs(profileId,i.getAccountId(),i.getCategoryId()); return toResponse(repo.save(i)); }
@Transactional
public void delete(UUID userId, UUID profileId, UUID itemId){ ensureProfile(profileId,userId); var item=repo.findByIdAndProfileId(itemId,profileId).orElseThrow(()->new NotFoundException("Item no encontrado")); var matches=matchRepo.findByProfileIdAndMonthlyPlanItemIdIn(profileId,List.of(itemId)); if(!matches.isEmpty()) matchRepo.deleteAll(matches); repo.delete(item); }
@Transactional
public MonthlyPlanItemResponse convert(UUID userId, UUID profileId, UUID itemId){ ensureProfile(profileId,userId); var i=repo.findByIdAndProfileId(itemId,profileId).orElseThrow(()->new NotFoundException("Item no encontrado")); if(i.getTransactionId()!=null) throw new BadRequestException("Item ya convertido"); if(i.getStatus()==MonthlyPlanItem.Status.CANCELLED) throw new BadRequestException("Item cancelado"); if(i.getType()==MonthlyPlanItem.Type.TODO||i.getType()==MonthlyPlanItem.Type.TRANSFER||i.getType()==MonthlyPlanItem.Type.RECOVERY) throw new BadRequestException("Tipo no convertible automáticamente"); var amount=i.getAmount()!=null?i.getAmount():(i.getMinAmount()!=null&&Objects.equals(i.getMinAmount(),i.getMaxAmount())?i.getMinAmount():null); if(amount==null||i.getAccountId()==null||i.getCategoryId()==null) throw new BadRequestException("Falta cuenta/categoría/monto exacto"); MoneyTransaction.MovementType mt=switch(i.getType()){case INCOME->MoneyTransaction.MovementType.INCOME; case EXPENSE,DEBT->MoneyTransaction.MovementType.EXPENSE; case SAVING->MoneyTransaction.MovementType.SAVING; default->null;}; if(mt==null) throw new BadRequestException("Tipo no convertible"); var st=(i.getStatus()==MonthlyPlanItem.Status.PAID||i.getStatus()==MonthlyPlanItem.Status.COLLECTED)?MoneyTransaction.Status.CONFIRMED:MoneyTransaction.Status.PENDING; var tx=txRepo.save(MoneyTransaction.builder().profileId(profileId).accountId(i.getAccountId()).categoryId(i.getCategoryId()).movementType(mt).realDate(i.getExpectedDate()==null?LocalDate.now():i.getExpectedDate()).budgetDate(LocalDate.of(i.getPeriodYear(),i.getPeriodMonth(),1)).amount(amount).currency(i.getCurrency()).description(i.getTitle()).origin(MoneyTransaction.Origin.SYSTEM).status(st).build()); i.setTransactionId(tx.getId()); i.setStatus(i.getType()==MonthlyPlanItem.Type.INCOME?MonthlyPlanItem.Status.COLLECTED:MonthlyPlanItem.Status.PAID); var saved=repo.save(i); matchRepo.findByProfileIdAndMonthlyPlanItemIdAndMoneyTransactionId(profileId,saved.getId(),tx.getId()).orElseGet(() -> matchRepo.save(MonthlyPlanTransactionMatch.builder().profileId(profileId).monthlyPlanItemId(saved.getId()).moneyTransactionId(tx.getId()).matchedAmount(amount).matchType(MonthlyPlanTransactionMatch.MatchType.SYSTEM_CONVERSION).confidence(MonthlyPlanTransactionMatch.Confidence.HIGH).build())); return toResponse(saved); }
}
