package com.hogaria.service;

import com.hogaria.dto.*;import com.hogaria.entity.MoneyTransaction;import com.hogaria.exception.*;import com.hogaria.repository.*;import java.time.LocalDate;import java.util.*;import org.springframework.stereotype.Service;
@Service
public class TransactionService {
  private final MoneyTransactionRepository repository; private final FinancialProfileRepository profileRepository; private final AccountRepository accountRepository; private final CategoryRepository categoryRepository;
  public TransactionService(MoneyTransactionRepository repository, FinancialProfileRepository profileRepository, AccountRepository accountRepository, CategoryRepository categoryRepository){this.repository=repository;this.profileRepository=profileRepository;this.accountRepository=accountRepository;this.categoryRepository=categoryRepository;}
  public TransactionResponse create(TransactionCreateRequest r, UUID userId){ if(r.amount().signum()<=0) throw new BadRequestException("Amount must be positive"); validate(r.profileId(),r.accountId(),r.categoryId(),userId); return toResponse(repository.save(MoneyTransaction.builder().profileId(r.profileId()).accountId(r.accountId()).categoryId(r.categoryId()).movementType(r.movementType()).realDate(r.realDate()).budgetDate(r.budgetDate()).amount(r.amount()).currency(r.currency().toUpperCase()).description(r.description()).origin(r.origin()==null?MoneyTransaction.Origin.MANUAL:r.origin()).status(r.status()==null?MoneyTransaction.Status.CONFIRMED:r.status()).build())); }
  public List<TransactionResponse> list(UUID userId, UUID profileId, int year, int month){ ensureProfile(profileId,userId); var from=LocalDate.of(year,month,1); var to=from.withDayOfMonth(from.lengthOfMonth()); return repository.findByProfileIdAndBudgetDateBetween(profileId,from,to).stream().map(this::toResponse).toList(); }
  public TransactionResponse get(UUID userId, UUID txId){var tx=repository.findById(txId).orElseThrow(()->new NotFoundException("Transaction not found")); ensureProfile(tx.getProfileId(),userId); return toResponse(tx);}  
  public TransactionResponse update(UUID userId, UUID txId, TransactionUpdateRequest r){ var tx=repository.findById(txId).orElseThrow(()->new NotFoundException("Transaction not found")); ensureProfile(tx.getProfileId(),userId); if(r.amount()!=null && r.amount().signum()<=0) throw new BadRequestException("Amount must be positive"); if(r.accountId()!=null) tx.setAccountId(r.accountId()); if(r.categoryId()!=null) tx.setCategoryId(r.categoryId()); if(r.movementType()!=null) tx.setMovementType(r.movementType()); if(r.realDate()!=null) tx.setRealDate(r.realDate()); if(r.budgetDate()!=null) tx.setBudgetDate(r.budgetDate()); if(r.amount()!=null) tx.setAmount(r.amount()); if(r.currency()!=null) tx.setCurrency(r.currency().toUpperCase()); if(r.description()!=null) tx.setDescription(r.description()); if(r.origin()!=null) tx.setOrigin(r.origin()); if(r.status()!=null) tx.setStatus(r.status()); validate(tx.getProfileId(),tx.getAccountId(),tx.getCategoryId(),userId); return toResponse(repository.save(tx)); }
  public void delete(UUID userId, UUID txId){ var tx=repository.findById(txId).orElseThrow(()->new NotFoundException("Transaction not found")); ensureProfile(tx.getProfileId(),userId); repository.delete(tx); }
  private void validate(UUID profileId, UUID accountId, UUID categoryId, UUID userId){ ensureProfile(profileId,userId); if(!accountRepository.existsByIdAndProfileId(accountId,profileId)) throw new BadRequestException("Account does not belong to profile"); var c=categoryRepository.findById(categoryId).orElseThrow(()->new NotFoundException("Category not found")); if(c.getProfileId()!=null && !Objects.equals(c.getProfileId(),profileId)) throw new ForbiddenException("Category does not belong to profile"); }
  private void ensureProfile(UUID profileId, UUID userId){ profileRepository.findByIdAndUserId(profileId,userId).orElseThrow(()->new ForbiddenException("Profile does not belong to user")); }
  private TransactionResponse toResponse(MoneyTransaction t){ return new TransactionResponse(t.getId(),t.getProfileId(),t.getAccountId(),t.getCategoryId(),t.getMovementType(),t.getRealDate(),t.getBudgetDate(),t.getAmount(),t.getCurrency(),t.getDescription(),t.getOrigin(),t.getStatus(),t.getCreatedAt(),t.getUpdatedAt()); }
}
