package com.hogaria.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.hogaria.dto.*;
import com.hogaria.dto.TransactionImportDtos.*;
import com.hogaria.entity.*;
import com.hogaria.exception.*;
import com.hogaria.repository.*;
import java.io.*;import java.math.BigDecimal;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.*;
import org.apache.poi.ss.usermodel.*;import org.springframework.stereotype.Service;import org.springframework.web.multipart.MultipartFile;

@Service
public class TransactionImportService {
  private final FinancialProfileRepository profileRepository; private final AccountRepository accountRepository; private final CategoryRepository categoryRepository; private final MoneyTransactionRepository txRepository; private final ExcelImportBatchRepository batchRepository; private final ExcelImportRowRepository rowRepository; private final TransactionService txService; private final ObjectMapper objectMapper=new ObjectMapper();
  public TransactionImportService(FinancialProfileRepository p,AccountRepository a,CategoryRepository c,MoneyTransactionRepository t,ExcelImportBatchRepository b,ExcelImportRowRepository r,TransactionService txs){profileRepository=p;accountRepository=a;categoryRepository=c;txRepository=t;batchRepository=b;rowRepository=r;txService=txs;}

  public TransactionImportPreviewResponse preview(UUID userId, UUID profileId, UUID accountId, TransactionImportSource source, MultipartFile file, Integer year, Integer month) {
    profileRepository.findByIdAndUserId(profileId,userId).orElseThrow(()->new ForbiddenException("Profile does not belong to user"));
    if(!accountRepository.existsByIdAndProfileId(accountId,profileId)) throw new BadRequestException("Account does not belong to profile");
    var rows=parse(source,file,profileId,accountId,year,month);
    var batch=batchRepository.save(ExcelImportBatch.builder().profileId(profileId).originalFileName(file.getOriginalFilename()).currency("ARS").status(ImportBatchStatus.PREVIEWED).year(year).build());
    for(var r:rows){ try{ rowRepository.save(ExcelImportRow.builder().batchId(batch.getId()).sheetName(source.name()).rowNumber(r.rowNumber()).concept(r.rawDescription()).amount(r.amount()).status(ImportRowStatus.valueOf(r.status().name())).rawJson(objectMapper.writeValueAsString(r)).build()); }catch(Exception ignored){} }
    return summarize(batch.getId(),source,accountId,rows);
  }
  public TransactionImportPreviewResponse getBatch(UUID userId, UUID profileId, UUID batchId){ profileRepository.findByIdAndUserId(profileId,userId).orElseThrow(()->new ForbiddenException("Profile does not belong to user")); var batch=batchRepository.findById(batchId).orElseThrow(()->new NotFoundException("Batch not found")); if(!batch.getProfileId().equals(profileId)) throw new ForbiddenException("Batch does not belong to profile"); var rows=loadRows(batchId); return summarize(batchId, TransactionImportSource.valueOf(rows.get(0).source().name()), null, rows);}
  public TransactionImportCommitResponse commit(UUID userId, UUID profileId, UUID batchId, TransactionImportCommitRequest request){ profileRepository.findByIdAndUserId(profileId,userId).orElseThrow(()->new ForbiddenException("Profile does not belong to user")); var previewRows=loadRows(batchId); var map=new HashMap<Integer,TransactionImportPreviewRow>(); previewRows.forEach(r->map.put(r.rowNumber(),r)); int created=0,skipped=0,dups=0,failed=0; var ids=new ArrayList<UUID>();
    for(var c:request.rows()){ var p=map.get(c.rowNumber()); if(p==null||c.status()==RowStatus.SKIPPED){skipped++;continue;} if((c.amount()!=null?c.amount():p.amount()).signum()<=0){failed++;continue;} if((c.categoryId()==null&&p.suggestedCategoryId()==null)&&!request.createMissingFallbackCategory()){failed++;continue;} var desc=c.description()!=null?c.description():p.normalizedDescription(); var amount=c.amount()!=null?c.amount():p.amount(); var dup=txRepository.findByProfileIdAndBudgetDateBetween(profileId,p.realDate(),p.realDate()).stream().anyMatch(x->x.getAmount().compareTo(amount)==0&&Objects.equals(x.getDescription(),desc)); if(dup){dups++; if(request.skipDuplicates()) continue;}
      try{ var id=txService.create(new TransactionCreateRequest(profileId,Objects.requireNonNull(c.accountId(),"accountId required"), c.categoryId()!=null?c.categoryId():p.suggestedCategoryId(), c.movementType()!=null?c.movementType():p.movementType(), p.realDate(), p.budgetDate(), amount, p.currency(), desc, MoneyTransaction.Origin.IMPORT, MoneyTransaction.Status.CONFIRMED), userId).id(); ids.add(id); created++; }catch(Exception ex){failed++;}
    }
    return new TransactionImportCommitResponse(created,skipped,dups,failed,ids,List.of(),List.of());
  }

  private List<TransactionImportPreviewRow> loadRows(UUID batchId){ return rowRepository.findByBatchIdOrderByRowNumber(batchId).stream().map(r->{ try{return objectMapper.readValue(r.getRawJson(), TransactionImportPreviewRow.class);}catch(Exception e){return null;}}).filter(Objects::nonNull).toList(); }
  private TransactionImportPreviewResponse summarize(UUID batchId, TransactionImportSource source, UUID accountId, List<TransactionImportPreviewRow> rows){ int dup=0,sk=0,un=0,imp=0; for(var r:rows){ if(r.status()==RowStatus.DUPLICATE)dup++; else if(r.status()==RowStatus.SKIPPED)sk++; else if(r.status()==RowStatus.NEEDS_CATEGORY)un++; else if(r.status()==RowStatus.READY)imp++; } return new TransactionImportPreviewResponse(batchId,source,accountId,rows.size(),imp,dup,sk,un,rows,List.of(),List.of()); }
  private List<TransactionImportPreviewRow> parse(TransactionImportSource source, MultipartFile file, UUID profileId, UUID accountId, Integer year, Integer month){ try { return source==TransactionImportSource.BANCO_PROVINCIA?parseBancoProvincia(file,profileId,accountId,year,month):parseMercadoPagoCsv(file,profileId,accountId,year,month);} catch(Exception e){ throw new BadRequestException("Cannot parse file: "+e.getMessage()); } }
  private List<TransactionImportPreviewRow> parseBancoProvincia(MultipartFile file, UUID profileId, UUID accountId, Integer year, Integer month) throws Exception { var out=new ArrayList<TransactionImportPreviewRow>(); var wb=WorkbookFactory.create(file.getInputStream()); var sheet=wb.getSheet("report"); DateTimeFormatter f=DateTimeFormatter.ofPattern("d-MMM-uuuu",new Locale("es","AR")); boolean header=false; int idx=0; for(var row:sheet){ if(!header){ if("Fecha".equalsIgnoreCase(cell(row,0))&&"Descripción".equalsIgnoreCase(cell(row,1))) header=true; continue; } var dateTxt=cell(row,0); var desc=cell(row,1); var amtTxt=cell(row,2).replace(".","").replace(",", "."); if(dateTxt.isBlank()||desc.isBlank()||amtTxt.isBlank()) continue; BigDecimal signed=new BigDecimal(amtTxt); var d=LocalDate.parse(dateTxt.toLowerCase(new Locale("es","AR")),f); var m=signed.signum()<0?MoneyTransaction.MovementType.EXPENSE:MoneyTransaction.MovementType.INCOME; var ndesc=desc.toUpperCase(Locale.ROOT).trim(); var hash=hash("BP|"+profileId+"|"+accountId+"|"+d+"|"+ndesc+"|"+signed); idx++; out.add(new TransactionImportPreviewRow(idx,TransactionImportSource.BANCO_PROVINCIA,null,hash,d,LocalDate.of(year!=null?year:d.getYear(),month!=null?month:d.getMonthValue(),1),desc,ndesc,signed,signed.abs(),"ARS",m,null,"Falta de categoría",Confidence.LOW,RowStatus.NEEDS_CATEGORY,"",String.format("{\"saldo\":\"%s\"}",cell(row,3)))); }
  return out; }
  private List<TransactionImportPreviewRow> parseMercadoPagoCsv(MultipartFile file, UUID profileId, UUID accountId, Integer year, Integer month) throws Exception { var out=new ArrayList<TransactionImportPreviewRow>(); var lines=new String(file.getBytes(),StandardCharsets.UTF_8).split("\n"); if(lines.length<2) return out; var headers=lines[0].split(","); Map<String,Integer> ix=new HashMap<>(); for(int i=0;i<headers.length;i++)ix.put(headers[i].trim(),i); for(int i=1;i<lines.length;i++){ var cols=lines[i].split(","); if(cols.length<2) continue; var dt=value(cols,ix,"Fecha de aprobación"); if(dt.isBlank()) dt=value(cols,ix,"Fecha de origen"); var op=value(cols,ix,"ID de operación en Mercado Pago"); var ref=value(cols,ix,"Código de referencia"); var type=value(cols,ix,"Tipo de operación"); var val=value(cols,ix,"Valor de la compra"); if(val.isBlank()) val=value(cols,ix,"Monto neto de la operación"); if(dt.isBlank()||type.isBlank()||val.isBlank()) continue; var d=LocalDate.parse(dt.substring(0,10)); var signed=new BigDecimal(val.replace(".","").replace(",", ".")); var m=signed.signum()<0?MoneyTransaction.MovementType.EXPENSE:MoneyTransaction.MovementType.INCOME; var desc=(value(cols,ix,"Detalle de la venta")+" "+type).trim(); var ndesc=desc.toUpperCase(Locale.ROOT); var sourceId=!op.isBlank()?op:ref; var hash=hash("MP|"+profileId+"|"+accountId+"|"+sourceId+"|"+d+"|"+signed); out.add(new TransactionImportPreviewRow(i,TransactionImportSource.MERCADO_PAGO,sourceId,hash,d,LocalDate.of(year!=null?year:d.getYear(),month!=null?month:d.getMonthValue(),1),desc,ndesc,signed,signed.abs(),value(cols,ix,"Moneda").isBlank()?"ARS":value(cols,ix,"Moneda"),m,null,"Falta de categoría",Confidence.LOW,RowStatus.NEEDS_CATEGORY,"",lines[i])); }
  return out; }
  private String cell(org.apache.poi.ss.usermodel.Row r,int i){var c=r.getCell(i); if(c==null) return ""; return switch(c.getCellType()){case STRING->c.getStringCellValue().trim(); case NUMERIC->BigDecimal.valueOf(c.getNumericCellValue()).stripTrailingZeros().toPlainString(); default->"";};}
  private String value(String[] cols,Map<String,Integer> ix,String key){ var i=ix.get(key); return i==null||i>=cols.length?"":cols[i].replace("\"","").trim(); }
  private String hash(String s){ try{ var md=MessageDigest.getInstance("SHA-256"); var b=md.digest(s.getBytes(StandardCharsets.UTF_8)); var sb=new StringBuilder(); for(byte x:b) sb.append(String.format("%02x",x)); return sb.toString(); }catch(Exception e){ return UUID.randomUUID().toString(); } }
}
