import { Link, Navigate, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { EmptyState } from '../../../components/ui/EmptyState';
import { ErrorState } from '../../../components/ui/ErrorState';
import { useMonthlyPlanItemActions } from '../../../hooks/useMonthlyPlanItemActions';
import { useQuickCaptureFlow } from '../../../hooks/useQuickCaptureFlow';
import { useStructuredPlanItemDraft } from '../../../hooks/useStructuredPlanItemDraft';
import { MonthlyPlanItemsTable } from '../components/MonthlyPlanItemsTable';
import { MonthlyPlanningChecklist } from '../components/MonthlyPlanningChecklist';
import { PlanningMappingsAuditPanel } from '../components/PlanningMappingsAuditPanel';
import { QuickCapturePanel } from '../components/QuickCapturePanel';
import { QuickCapturePreviewForm } from '../components/QuickCapturePreviewForm';
import { StructuredPlanItemForm } from '../components/StructuredPlanItemForm';
import { usePlanningData } from '../hooks/usePlanningData';
import { canConvertPlanItem, getPlanItemMissingLabels } from '../planningUtils';
import { parseSortKey, parseStatusFilterKey, parseTableFilterKey, parseTypeFilterKey, preservePlanningPeriodParams } from '../planningSearchParams';
import { planningRoutes } from '../planningRoutes';
import { buildPlanningPath } from '../utils/buildPlanningPath';
export function MonthlyPlanItemsPage(){ const { profileId,year,month,items,accounts,categories,invalidatePlanningViews }=usePlanningData(); const draft=useStructuredPlanItemDraft(year,month); const actions=useMonthlyPlanItemActions({profileId,year,month,form:draft.form,resetFormAfterCreate:draft.resetAfterCreate,invalidatePlanningViews}); const [params]=useSearchParams(); return <MonthlyPlanItemsTable profileId={profileId} items={items} accounts={accounts} categories={categories} onConvert={actions.convert} onCancel={actions.cancel} onDelete={actions.remove} onUpdate={actions.update} onMarkPaid={actions.markPaid} onMarkCollected={actions.markCollected} pendingActionId={actions.pendingActionId} actionError={actions.actionErrorMessage} filter={parseTableFilterKey(params.get('filter'))} statusFilter={parseStatusFilterKey(params.get('status'))} typeFilter={parseTypeFilterKey(params.get('type'))} search={params.get('search') ?? ''} sortBy={parseSortKey(params.get('sort'))}/>; }
export function MonthlyPlanItemCreatePage(){ const { profileId,year,month,accounts,categories,invalidatePlanningViews,searchParams }=usePlanningData(); const draft=useStructuredPlanItemDraft(year,month); const nav=useNavigate(); const actions=useMonthlyPlanItemActions({profileId,year,month,form:draft.form,resetFormAfterCreate:draft.resetAfterCreate,invalidatePlanningViews}); return <StructuredPlanItemForm form={draft.form} setForm={draft.setForm} accounts={accounts} categories={categories} onCreate={async()=>{ await actions.createAsync(); nav(buildPlanningPath(planningRoutes.items(profileId), preservePlanningPeriodParams(searchParams))); }} isCreating={actions.isCreating} error={actions.createErrorMessage}/>; }
export function MonthlyPlanItemEditPage(){ const { profileId, items, accounts, categories, searchParams, year, month, invalidatePlanningViews } = usePlanningData(); const { itemId = '' } = useParams(); const nav = useNavigate(); const [params] = useSearchParams(); const item = items.find((current) => current.id === itemId); const draft=useStructuredPlanItemDraft(year,month); const actions=useMonthlyPlanItemActions({profileId,year,month,form:draft.form,resetFormAfterCreate:draft.resetAfterCreate,invalidatePlanningViews}); if (!itemId) return <ErrorState title='Parámetros inválidos' message='Falta itemId en la URL.'/>
if (!item) return <EmptyState title='Ítem no encontrado' message='El ítem ya no existe o no pertenece al período activo.'/>
return <MonthlyPlanItemsTable profileId={profileId} items={items} accounts={accounts} categories={categories} onConvert={actions.convert} onCancel={actions.cancel} onDelete={actions.remove} onUpdate={async(id,payload)=>{ await actions.update(id,payload); nav(buildPlanningPath(planningRoutes.items(profileId), preservePlanningPeriodParams(searchParams))); }} onMarkPaid={actions.markPaid} onMarkCollected={actions.markCollected} pendingActionId={actions.pendingActionId} actionError={actions.actionErrorMessage} focusedItemId={item.id} focusedMode={params.get('mode') ?? 'FULL'} filter='ALL' statusFilter='ALL' typeFilter='ALL' search='' sortBy='DATE'/>; }
export function MonthlyPlanImportPage(){ const { profileId,year,month,accounts,categories,invalidatePlanningViews }=usePlanningData(); const quick=useQuickCaptureFlow({profileId,year,month,invalidatePlanningViews}); return <QuickCapturePanel input={quick.quickText} onChange={quick.setQuickText} onAnalyze={quick.analyze} canAnalyze={quick.canAnalyze} error={quick.quickError} showDiscard={quick.hasPreview} onDiscard={quick.discard} onClear={quick.clear} isAnalyzing={quick.isAnalyzing}>{quick.quickPreview && quick.quickForm ? <QuickCapturePreviewForm profileId={profileId} preview={quick.quickPreview} form={quick.quickForm} setForm={quick.setQuickForm} accounts={accounts} categories={categories} onConfirm={quick.confirm} isConfirming={quick.isConfirming} error={quick.commitError}/> : null}</QuickCapturePanel>; }
export function MonthlyPlanAlertsPage(){ const { summary,items,accounts,categories,profileId,searchParams }=usePlanningData(); const navigate = useNavigate(); const onApply = (key: 'UNPRICED'|'MISSING_CLASSIFICATION'|'READY_TO_CONVERT'|'DUE_NEXT_7_DAYS'|'ALL') => { const next = preservePlanningPeriodParams(searchParams); if (key === 'READY_TO_CONVERT') navigate(buildPlanningPath(planningRoutes.convert(profileId), next)); else { next.set('filter', key); navigate(buildPlanningPath(planningRoutes.items(profileId), next)); } }; return <section className='planning-section-stack'><MonthlyPlanningChecklist summary={summary} items={items} onApply={onApply}/><PlanningMappingsAuditPanel profileId={profileId} items={items} accounts={accounts} categories={categories} periodParams={preservePlanningPeriodParams(searchParams)} /></section>; }
export function MonthlyPlanConvertPage(){ const {items,profileId,year,month,invalidatePlanningViews,searchParams }=usePlanningData(); const draft=useStructuredPlanItemDraft(year,month); const actions=useMonthlyPlanItemActions({profileId,year,month,form:draft.form,resetFormAfterCreate:draft.resetAfterCreate,invalidatePlanningViews}); const convertible = items.filter(canConvertPlanItem); const blocked = items.filter((item) => !canConvertPlanItem(item)); const editLink = (id: string, mode: 'classification'|'amount') => buildPlanningPath(`${planningRoutes.itemEdit(profileId,id)}?mode=${mode}`, preservePlanningPeriodParams(searchParams)); return <section className='panel'><h2>Revisión de conversión</h2><ul>{convertible.map((item)=><li key={item.id}><strong>{item.title}</strong><button type='button' className='boton-principal' disabled={actions.pendingActionId===item.id} onClick={()=>actions.convert(item.id)}>Convertir</button></li>)}</ul><h3>Bloqueados</h3><ul>{blocked.slice(0,20).map((item)=><li key={item.id}>{item.title} — {getPlanItemMissingLabels(item).join(', ')} <Link to={editLink(item.id, !item.amount && !item.minAmount ? 'amount' : 'classification')}>Corregir datos</Link></li>)}</ul></section>; }
export function LegacyPlanningRedirect(){ const { profileId='' }=useParams(); const [searchParams]=useSearchParams(); return <Navigate to={buildPlanningPath(planningRoutes.root(profileId), searchParams)} replace/>; }
